project:
  type: book
  
book:
  title: "행복방법론"
  author: "안도현"
  date: "2023. 9. 17."
#  image: image1.jpg

#  navbar: 
#    search: true
#    right:
#    - icon: guthub
#      href: https://github.com
#    aria-label: Github
  
  sidebar:
    style: docked
    background: light
    search: true

  chapters:
    - index.qmd
    - intro.qmd
    - part: part1.qmd
      chapters:
        - ch01-moral.qmd
        - ch02-power.qmd
        - ch03-attract.qmd
        - ch04-love.qmd
        - ch05-desire.qmd
        - ch06-suicide.qmd
        - ch07-choice.qmd
        - ch08-edu.qmd
        - ch09-entertain.qmd
        - ch10-happiness.qmd
    - part: part2.qmd
      chapters:
        - ch11-happiness2.qmd
        #- ch11b-happiness2eng.qmd
        - ch12-swb.qmd
        #- ch12b-swbeng.qmd
        - ch13-pwb.qmd
        #- ch13b-pwbeng.qmd
    - part: part3.qmd
      chapters: 
        - summary.qmd
        - references.qmd

page-navigation: true      

comments:
  hypothesis: true
  
bibliography: references.bib

format:
  html:
    theme: zephyr
  #  cover-image: cover1.jpg
  #  code-fold: true
  #  code-tools: true
  #  code-block-border-left: true
  #  code-overflow: scroll
  
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex    
        
execute: 
  echo: true
  cache: false
  warning: false
  message: false

server: shiny



