# 사랑

## 연애세포란게 있을까?

“솔로 오래가면 ‘연애세포’ 죽는다”
재치넘치는 블로그 ‘loading 100%…’에 소개된 유머다. ‘loading 100%…’는 몇 장의 사진을 재치 있게 이야기로 엮어 재미를 배가한다. 이 블로그는 “사랑은 밀고 당기는 거랍니다. 참 쉽죠잉~”라며 “솔로 오래가면 ‘연애세포’ 죽는다” 라는 기사를 인용했다. 어느 매체인지 찾을 수는 없지만, “솔로 오래가면 ‘연애세포’ 죽는다”로 검색해 보면, 많은 솔로들의 연애에 대한 관심을 확인할 수 있다. 정말로 ‘연애세포’라는 게 있을까 하는 궁금증들이다. 과연 연애 세포라고 할 수 있는 것이 있을까? 있을 듯 하다. 인간의 모든 활동은 1천억 신경세포의 작용이기 때문이다. 연애는 인간의 활동이니, 당연히 연애와 관련된 신경세포가 분명 있어야 한다. 문제는, 연애만 전문적으로 관여하는 연애 전문 신경세포가 따로 있는지의 여부다. 
연애란 무엇일까? 국어사전에는 “연애(戀愛) [명사] 남녀가 서로 애틋하게 그리워하고 사랑함”이라고 정의돼 있다. 국어사전에 따르면, 연애에는 5가지 요소가 있다. (1) 남자와 여자, (2) 서로, (3) 애틋, (4) 그리움, (5) 사랑. 즉, 연애는 남녀간의 사랑인데, 그 사랑 중에서도 서로 애틋하게 그리워하는 사랑을 말한다. 사람의 모든 생각, 느낌, 행동은 바로 신경세포들의 작용이다. 따라서, 연애세포는 남자와 여자가 서로를 애틋하게 그리워하는데 관여하는 사랑전문 신경세포라고 할 수 있다. 

## 사랑이란?
사랑에 대한 과학적 접근은 한편으론 흥미롭지만, 다른 한편으론 그다지 매력적이지 않은 점이 있다. 사랑은 무엇인가 신비한 영역으로 남겨두고 싶은 구석이 있기 때문이다. 1975년 미국에서 엘런 버실드와 일레인 햇필드라는 두 젊은 과학자가 사랑에 대한 과학적 탐구에 대해 국립과학재단의 연구기금 8만 4천달러를 받았을 때, 윌리엄 프록시머 위스콘신주의 상원의원이 격렬하게 반대했다. 이유는 알고 싶지 않아서였다. (“I am also against it because I don’t want the answer.”) 사랑은 삶의 신비로운 영역으로 남겨두고 싶었기 때문이었다. 왜 그리고 어떻게 남자와 여자가 사랑에 빠지는지에 대한 과학적 이해가 사랑의 낭만을 깨뜨릴 것 같은 두려움이었다. 당시, 미국 언론매체 시카고 트리뷴은 버실드/햇필드의 연구계획과 프록시머의 비판을 소개하며 여론조사를 했는데, 독자의 88%가 프록시머의 비판에 동조했다  (Cited from Peterson, 2006). 그럼에도 불구하고, 사랑에 대한 과학적 이해는 필요하다. 과연 첫눈에 반한 것을 정말로 사랑이라 할 수 있는지, 욕정도 사랑에 끼워줄 수 있는지 대답은 사랑에 대한 과학적 탐구를 통해 제대로 이해할 수 있다. 게다가, 사랑은 아름다운 면만 지니고 있는 게 아니다. 사랑을 얻지 못한 사람도 있고, 사랑을 잃은 사람도 있다. 사랑에 대한 정확하게 알아야, 사랑을 잘 할 수 있고, 사랑의 아픔에서 벗어날 수 있기도 하다.
사랑을 과학적으로 이해하는 한 방식이 진화의 관점이다. 모든 생물은 생존과 관련 다양한 선택을 하게 되는데, 이 과정에서 생존과 번영에 유리한 특질이 후대로 전달된다는 접근 방식이다. 진화의 접근은 장점이 많다. 생물학과 신경과학의 성과를 활용, “왜”에 대한 질문에 해답을 내놓을 수 있기 때문이다. 남녀간의 사랑에 대한 과학적 접근으로 유명한 학자가 미국 럿거즈 대학 헬렌 피셔다. 피셔는 여성의 성의 진화와 성과 핵가족의 기원에 대한 연구로 박사학위를 받은 인류학자다. 피셔에 따르면, 사랑은 일종의 짝짓기 전략이다. 사랑을 무엇인가 신비로운 것으로 남겨두고 싶은 사람들에겐 그리 편안한 주장이 아니겠지만 말이다. 그러나, 사람들에게 짝을 이루는 것만큼 고귀한 일이 따로 있을 것 같지 않다. 고대에서 현재까지 수많은 사랑이야기가 예술작품에서 빠진 적이 없고, 안방 드라마에서 사랑이야기를 빼면 남는 게 없어지고, 사랑과 관련된 다양한 의례가 있는 것도 사랑이 “무엇인가 신비한” 것이기 때문이 아니다. 우리 인간이 생명을 이어가기 위한 핵심이기 때문이다. 기꺼이 사랑을 위해 살고, 사랑을 위해 죽기를 마다하지 않는 것도 이런 이유에서다. 삶만큼 고귀한 게 무엇이 있으랴!
피셔는 사랑, 즉 짝짓기와 재생산과 관련된 두뇌 시스템을 세가지로 구분한다 (Fisher 1998). 가장 원초적인 게 섹스에 대한 욕망이다. 섹시한 이성이기만 하면 느끼는 욕정(Lust)이다. 두번째가 연인에 대한 집착 (낭만적 사랑)이다. 특정 개인과의 관계를 형성하기 위한 단계라 할 수 있다. 낭만적 사랑은 개인의 에너지(특히 섹스에 대한 에너지)를 한 순간 특정여성, 혹은 특정 남성에 쏟아 붇게 하는 역할을 한다. 세번째가 정(情: Attachment)이다. 오랜 관계를 통해 형성된 안정적인 관계를 이룬 단계이다. 이때는 “살아주는” 단계라 할 수 있다. 피셔는 이를 다음과 같이 묘사했다. “세번째 두뇌 시스템은 당신으로 하여금 ‘이 인간’을 감내할 수 있도록 형성됐다. 함께 사는 사람을 인간으로 여길 수 있도록 진화한 두뇌 시스템이란 것이다. 결혼한지 3-4년쯤 되면, 화가 나고, 실망도 하고, “그 놈의 정” 때문에 서로의 단점을 용인해주는 단계라 하면 그다지 과장된 게 아닐 게다. 사람들은 욕정, 낭만적 사랑, 정 등 세가지 두뇌시스템을 통해 사랑에 빠진다. 그러나, 순서는 사람마다 다르다. 성관계부터 맺은 다음, 사랑에 빠지는 사람이 있는가 하면, 오랜 시간에 걸쳐 정들었다가, 사랑에 빠져 성관계를 맺는 경우도 있다. 

## 연애세포?
연애세포는 사랑과 관련된 신경세포다. 사람의 뇌에는 약 1천억에서 1천5백억 개의 신경세포가 있다. 모든 신경세포들이 서로 연결돼 있는 게 아니다. 서로 연결된 신경세포는 약 1만개 정도된다. 신경세포는 다른 신경세포에서 정보를 받아, 이를 다시 다른 신경세포로 연계해 준다 (신경세포 그림). 신경세포의 돌기(dendrite)라고 하는 부분에서 정보를 받아, 축색(axon)으로 내보낸다. 그런데, 돌기와 축색은 직접적으로 닿아 있지 않다. 시냅스라고 하는 미세한 간극이 있다. 축색에서 시냅스에 도파민과 같은 신경전달물질을 분비하면, 돌기의 수용체가 분비된 신경전달물질을 붙잡는다. 축색의 신경전달물질이 분비되기 위해서는 전기신호가 필요하다. 이를 액션포텐셜(Action Potential)이라고 한다. 인간의 모든 생각, 느낌, 행동은 바로 이러한 신경세포의 전기화학작용을 통해 이뤄진다. 따라서, 이 전기신호를 측정하는 것이 신경세포의 활동을 알 수 있는 가장 직접적인 방법이다. 뇌에 전극을 심어 신경세포 하나 하나의 활동을 측정하는 방식이다. 그런데, 이렇게 뇌에 전극을 심으면, 생명에 영향을 미치기 때문에 동물들을 대상으로 제한적으로 사용한다. 치료목적으로 환자의 두뇌에 전극을 심어 사람의 신경세포활동을 직접적으로 측정하는 경우도 있다. 간접적으로 신경세포의 활동을 측정하는 방식도 있다. 신경세포가 활동하기 위해서는 산소가 필요하다. 몸의 20%정도의 산소를 사람의 두뇌가 소모하지만, 뇌는 산소를 저장하지 않는다. 뇌에는 혈액을 통해 산소가 끊임없이 공급돼야 한다. 기능성 자기공명장치 (fMRI: functional Magnetic Resonance Imaging)는 강력한 자기장을 발생시켜 신경세포에 조달되는 혈액의 산소 소모량을 측정하는 장치다. 신경세포의 활동을 직접적으로 측정하는 것은 아니지만, 해상도가 좋아 널리 쓰인다. 
연애세포를 찾기 위한 연구도 fMRI를 이용했다 (Fisher et al. 2002). 피셔는 사랑에 빠진 연인들의 뇌를 분석하기 위해, 1-2년 정도 사랑에 푹 빠진 연인들을 찾아야 했다 (주: 피셔는 TED.com 강연에서 그의 연구에 얽힌 이야기를 소개했다). 우선, 미국 뉴욕 일대에 “사랑에 푹 빠진 사람을 찾는다”는 전단지도 돌리고, 소문도 내 서로 미치도록 사랑하는 연인들을 모집했다. 이들을 실험실로 초대한 후 피셔가 정말로 서로를 미치도록 사랑하는지 아닌지 판단하기 위해 사용한 질문은 두 종류. 우선, “하루 종일 밤낮으로 얼마나 이 사람(참가자의 연인)에 대해 생각합니까”라고 물었다. 사랑에 빠진 사람들은 한결같이 “하루종일”이라고 대답했다. 그녀 (혹은 그 남자)에 대한 생각을 한 순간도 멈출 수 없다는 것. 또 다른 질문은 “연인을 위해 죽을 수 있냐”는 질문에 “그렇다”고 대답하면, 사랑에 눈먼 사람으로 간주, 피셔교수의 뇌영상장치(fMRI) 안에 누워, 그들의 사랑에 빠진 뇌를 보여주었다. 
이렇게 걸러진 연인들의 뇌를 여러 사진을 보여주며 분석했다. 사랑에 빠진 사람의 사진을 보았을 때와 중립적인 사진을 보여준 다음, 뇌의 반응의 차이를 분석했다. 뇌의 여러 부분이 반응하는데, 그 중에서도 특별한 반응을 보여주는 곳이 있다. 오른쪽 복측피개야(Vental Tegmental Area: VTA)와 선조체(Striatum)였다. 복측피개야는 도파민이라는 신경전달물질이 생성되는 곳으로, 선조체 등에 있는 신경세포에 도파민을 분비한다. 도파민은 동작 인지 보상 등 다양한 기능을 하는데, 복측피개야에서 생산돼 선조체로 분비되는 도파민은 보상과 동기부여에 핵심적인 역할을 한다. 즉, 도파민은 생명체가 생존과 번영에 도움이 되는 것을 찾는 과정과 결과에 보상을 느끼도록 하는 물질이라고 할 수 있다. 화폐와 같은 역할을 한다고 보면 된다. 가치있는 상품에 돈이 몰려 비싼 값에 거래되는 것처럼, 도파민이 몰리면 가치 있는 것이라고 신호를 보내는 것이라 할 수 있다. 그 신호가 바로 ‘쾌락’이다. 어떤 대상에 대한 느낌 (쾌락 혹은 불쾌)을 통해 생존에 도움이 되는지 아닌지 판단한다는 것 (주: 탐욕 등 쾌락 자체를 추구하면 생존에 도움이 되지 않는다. 쾌락은 신호로서 역할을 해야 하는데, 신호 자체를 추구하기 때문에 문제가 생긴다. 예를 들어, 파란불은 길을 안전하게 건널 수 있다는 신호다. 파란 불을 안전하다고 느끼고, 길을 건너야 하는 게 정상이다. 쾌락을 위한 쾌락의 추구는 파란불의 안전한 느낌만 추구하고, 길을 건너지 않는 것에 비유할 수 있다.) 짝짓기는 생명을 이어가는 핵심적인 역할을 하므로, 짝을 찾고 이루는 과정에 도파민이 몰리는 것이다. 낭만적 사랑이 오직 한 사람에 대한 열정이란 점에서 도파민의 역할과 일치한다. 특정인을 향해 도파민이 분비됨으로써, 열정과 에너지를 낭비하지 않도록 해준다. 이 사람, 저 사람에 기웃거리지 않게 되기 때문이다. 그만큼 생존과 번영에 유리하다는 것이다 (Fisher, 2006).

## 욕정은 사랑일까?
사랑과 성은 밀접하다. 실제로 욕정은 사랑으로 이어지곤 하지만, 욕정과 사랑은 구분된다. 욕정은 성적 욕구를 충족시키기 위한 충동이다. 반면 낭만적 사랑은 특정한 사람을 향한 열정이다. 욕정의 목표는 성적결합인 반면, 낭만적 사랑의 목표는 정서적 결합이다. 욕정은 충족되면, 당분간 성관계에 대한 욕구가 가라앉는다. 그러나, 낭만적 사랑에는 충족이란 게 없다. 애인과 성적 결합이 있다 해서, 사랑이 가라앉지는 않는다. 오히려, 서로에 대한 열망이 더욱 더 뜨거워진다. 이런 이유로, 적지 않은 사람들이 낭만적 사랑 없이 성관계를 맺기도 하고, 성관계 없이도 낭만적 사랑을 유지한다. 이런 의미에서 처음 만나 성관계를 맺는 것은 사랑으로 발전할 수 있는 있어도, 사랑은 아니라고 할 수 있다. 무엇보다 욕정과 사랑이 다른 점은 그 대상이다. 욕정의 대상은 넓다. 성적으로 매력적이기만 하면 욕정의 대상이 된다. 욕정은 일종의 탐색을 위한 에너지다. 욕정과 낭만적 사랑에 관여하는 화학물질도 다르다. 낭만적 사랑은 주로 도파민의 작용인 반면, 욕정은 주로 성홀몬(안드로젠과 에스트로젠)의 작용이다. 실제로 성홀몬을 투여했을 때 성에 대한 욕구는 증가하지만, 특정인에 대한 성적 선호도나 낭만적 사랑으로 이어지지는 않는다 (Fisher 1998).
낭만적 사랑은 특정인과의 관계다. 욕정의 대상은 특정인이 아니다. 낭만적 사랑의 가장 큰 특징은 특정한 사람에 대한 집착이다. 피셔는 사랑에 빠지면 세가지 증상이 나타난다고 한다. 우선, 연인에 특별한 의미를 부여한다. “이 세상에 새로운 중심이 생겼는데, 그 중심은 바로 매리 앤!”이라고 고백한 피셔의 실험참가자처럼 말이다. 이를 두고, 재담가 조지 버나드 쇼는 “사랑에 빠지면 한 여인과 다른 여인들의 차이를 과장하는 것”이라고 했다. 세상의 여자는 다를 바 없는데, 사랑에 빠지면, 연인만 특별해 보인다는 것이다. 우리말에 “눈에 콩깍지가 씌웠다”는 말이 여기에 해당된다. 14세기 영국 문학가 쵸서(Chaucer)의 말처럼 사랑은 사람을 눈멀게 한다. 우리말에도 “맹목적인 사랑”이란 표현이 있다. 그 다음 증상은 연인에 대한 집중. 연인이 좋아하는 것은 다 좋아하게 된다. 쇼핑이라면 “두드러기”가 나는 남자도 사랑에 빠졌을 때는 쇼핑이 취미가 된다. 또 다른 사랑의 증세는 상대에 대한 소유욕. 사랑하는 사람에 대해 강박적으로 생각하고, 온 종일 함께 있고 싶어하는 마음이 생긴다. 사랑의 또 다른 증상은 힘이 난다는 것이다. 그녀, 혹은 그에게 집중하고 몰두하면서 삶에 활력이 생기고 몸 안에 에너지가 충만해지는 듯한 느낌이 드는 것이다. 피셔는 낭만적 사랑은 성적으로, 감정적으로 “미친” 상태라고 한다. 상대방에 대해 비이성적으로 집착하게 된다 (Fisher, 2006). 
왜 사람들은 사랑에 빠지면 한 사람에 대해 “미친”상태에 빠지게 되는 것일까? 진화의 관점에서 보면, 오직 한 사람만 미치도록 사랑하는 것이 생존과 번영을 위한 최적의 선택이기 때문이다. 사람은 다른 동물들과 달리 홀로 서기까지 오랜 세월이 필요하다. 부모의 보살핌이 없으면 살아남기 어렵다. 아버지와 어머니의 관계가 좋아야 아이들이 잘 자랄 수 있다. 여자의 입장에서 오직 ‘나’에게 헌신적인 남자가 본인과 아이를 지켜줄 만한 사람이라고 믿을 수 있다. 남자의 입장에서도 오직 ‘나’만을 바라 보는 여자가 다른 남자의 아이를 ‘나’의 아이라고 속이지 않을 것이라 믿을 수 있다. 욕정에는 묘한 구석이 있다. 피셔는 욕정 그 자체는 사랑이 아니지만, 사랑에 빠지도록 하는 강력한 요인이라고 지적한다. 성관계를 통한 쾌락은 단지 일시적으로 끝나는 쾌락이 아니기 때문이다. 그 쾌락은 상대방에 대해 좋은 느낌을 갖게 해주고, 애정을 느끼도록 하기 때문이다. 실제로, 사랑의 도파민과 욕정의 성홀몬의 작용이 완전하게 분리된 게 아니다. 안드로젠과 에스트로젠이 증가하면, 도파민의 분비로 이어지고, 도파민의 증가는 안드로젠과 에스트로젠의 분비로 이어진다. 이런 점에서 캐주얼 섹스는 캐주얼하지 않다. 성관계를 맺은 사람에게 특별한 의미를 부여하는 강력한 계기가 되기 때문이다.

## 사랑과 정
흔히 사랑이라 할 때 이성간의 뜨거운 낭만적 사랑을 말한다. 낭만적 사랑은 용접에 비유할 수 있다. 용접은 뜨거운 불로 쇠를 녹여 두 물체를 단단하게 붙인다. 낭만적 사랑도 마찬가지다. 뜨거운 열정으로 서로 다른 두 사람이 끈끈한 정으로 묶인다. 우리말의 정(情)에 해당하는 말이 영어단어의 ‘Attachment’다. ‘Attach’는 무엇인가에 붙이는 것을 말한다. 우리 말에도 ‘애착(愛着)’이란 단어가 있다. 즉, 정이란 뜨거운 낭만적 사랑이 없어도, 두 사람이 떨어지기 않게 묶어두는 것을 말한다. 뜨거운 낭만적 사랑과 끈끈한 정은 아프리카 칼라하리 사막의 부시맨 여성 니사가 잘 묘사하고 있다 (Shostak, 1981). 그녀에게도 사랑은 두가지가 있다. 니사는 두 사람이 처음 함께 할 때는 마음이 불같이 타올라, 그 열정은 대단하다고 묘사한다. 그러나, 시간이 흐르면서, 그 불 같은 열정은 식는다. 계속 서로를 사랑하지만, 그 방식은 바뀐다. 따스하고 의존할 수 있도록 말이다. 
한눈에 반해 하룻밤을 함께 보냈다면, 사랑에 빠졌던 것이 아니다. 욕정에 따른 행동이다. 성관계는 하룻밤의 관계로 끝나기도 하지만, 두 사람의 관계를 특별하게 만든다. 욕정은 성홀몬의 작용이지만, 성관계는 성홀몬 분비 이상의 의미가 있다. 성적흥분과 만족을 통해 뇌에 도파민이 분비되는데, 이는 두 사람의 관계를 특별한 것으로 만든다. 도파민의 역할이 어떤 대상에 가치를 부여하는 것이기 때문이다. 이런 점에서 도파민 분비와 관련된 복측피개야(VTA)와 선조체에 몰려 있는 신경세포들이 욕정을 사랑으로 발전하도록 하는 연애세포라고 할 수 있다. 그런데, 연애는 몇 번의 성관계로 끝나는 단기적 관계가 있다. 아주 오랜 기간 함께 살을 맞대고 살아야 할 사람과의 관계를 만드는 과정이다. 연애에는 뜨거운 불도 필요하지만, 용접봉도 필요하다. 뜨거운 불이 두 쇠붙이와 쇠붙이 사이에 용접봉을 적당히 녹여 내야 한다. 뜨거운 불을 적당하게 조절 해야 한다는 것. 사랑도 마찬가지다. 
도파민 시스템에 있는 연애세포는 뜨거운 불에 해당한다. 낯선 남자와 낯선 여자 사이의 어색함을 녹여 뜨거운 관계로 만드는 역할을 한다. 그런데, 이 뜨거운 불에는 조절이 필요하다. 따라서, 이런 조절 역할을 하는 신경세포들 역시 연애세포라고 할 수 있다. 전전두엽과 두정엽에 이런 역할을 하는 신경세포들이 몰려 있다. 특히, 앞쪽뇌라고 하는 전전두엽에 많다. 신경세포는 여러 종류의 신경전달물질을 통해 작동한다. 크게 세가지로 구분되는데, 뭔가를 하게 만드는 것(흥분작용; Excitation)과, 하지 못하게 하는 것(억제작용; inhibition), 그리고, 이들 흥분작용과 억제작용을 제어하는 조절작용(Regulation)이다. 두뇌 작용은 이 세가지 흥분작용, 억제작용 및 조절작용이 고도로 정교한 균형을 이루는 과정이라 할 수 있다. 왜 복잡하냐 하면, 신경세포의 작동이 이중 삼중 사중의 제어를 거치기 때문이다. 여기서, 핵심은 제어, 조절, 통제다. 인간이 인간답게 살수 있는 것은 바로 두뇌가 고도의 제어시스템을 갖추었기 때문이다. 연애도 바로 고도의 제어시스템의 작동과정이라 할 수 있다. 한편에서는 특정 개인을 향한 욕망이 끓어오르면서, 그를 위해 에너지를 쏟아 붇도록 하는 신경세포들과, 그 에너지를 적절하게 조절하면서, 상대와의 관계를 쌓아가는 신경세포들간의 균형작용이다. 이런 점에서 연애세포는 특정한 세포라기 보다, 연애에 관여하는 일군의 열정과 관계의 신경세포집단이라 할 수 있다.
그렇다면, 솔로로 오래 지내면 이런 신경세포들이 죽을까? 그렇지는 않을 것 같다. 이 신경세포들이 연애만을 위해 특별하게 존재하는 게 아니기 때문이다. 임자 만나면 언제든 작동한다. 다만, 그 신경세포들이 제대로 작동하도록 평상시 단련해 놓는 것이 좋다. 열정은 누구나 갖고 있기 때문에 특별한 단련이 없어도 된다. 문제는 전전두엽에 몰려있는 관계의 신경세포들이다. 평소에 이 신경세포들을 단련시키지 않으면, 비실거린다. 이 놈들이 비실거리면, 연애하기 참 힘들다. 즉, 연애 잘하려면 전전두엽을 단련해야 한다고 할 수 있다. 

