# 자살

## 욕망의 상실{.unnumbered}

## 관계의 단절
세상엔 역설적인 게 참 많지만, 자살만큼 풀기 쉽지 않은 역설도 없다. 생명이 가장 소중하다고 하는데, 스스로 그 생명을 끊으니 말이다. 더욱 역설적인 것은 그런 역설적 현상이 꽤나 빈번하다는데 있다. 

세계보건기구에 따르면, 매년 스스로 목숨을 끊는 사람이 1백만 명이나 된다. 40초마다 한명씩 자살로 생을 마감하는 셈 전쟁 등과 같은 무력충돌로 인한 사망자수보다도 많다. 

게다가 지난 45년간 자살률이 60%나 늘었다. 그런 역설적 현상이 한국을 비롯한 아시아 지역이 유럽 지역의 국가에서 보다 더 빈번하다고 한다 (그림1 @ http://www.who.int/mental_health/prevention/suicide/suicideprevent/en/). 유럽지역 내에서도 동유럽이 서유럽보다 높다. 러시아, 중국, 일본, 한국 등 집단주의 문화권의 자살률이 높다. 

더욱 안타까운 일은 가장 삶에 대한 애착이 강해야 할 10대와 20대의 자살률이 크게 늘고 있는 현상이다. 10세에서 24세 사이의 집단에서 자살이 두번째 주요 사망원인으로 꼽히고 있다. 

젊은 층의 자살률이 증가하긴 했지만, 노년층에서 자살률이 가장 높다. 실업 상태인 사람들의 자살률 또한 높다. 이혼한 사람들의 자살위험도 역시 높다. 교도소에 수감됐을 때 자살위험이 커진다. 가장 위험한 순간은 독방에 갇혔을 때다 (Hawton & van Heerigen 2009). 

집단주의 문화권, 노년층, 실업자, 독방에 갇힌 수감자에게서 빈번하게 자살이 발생한다는 사실을 통해 사람들이 왜 스스로 목숨을 끊는지 알 수 있는 단서를 찾을 수 있다. 

이들의 공통적 요소는 관계의 단절이다. 교도소에 수감된다는 것 자체가 사회에서 격리되는 것인데, 독방에 수감되는 것은 관계가 끊어지는 극단적 사례에 속한다. 

실업상태 역시 관계의 단절이다. 사람에게 일자리가 있다는 것은 단지 먹고 살고 있는 수단확보 그 이상의 의미가 있다. 어딘가에 소속된다는 것이 되기 때문이다. 

일을 통해 사람들은 다른 사람과 관계가 안정적으로 형성된다. 이혼 역시 중요한 사회적 관계가 끊어지는 사건이다. 나이가 든다는 것 역시 관계의 단절이다. 퇴직을 통해 함께 일하던 사람과의 관계가 단절될 뿐 아니라, 가족과 친구가 하나 둘씩 이 세상을 떠나가기 때문이다. 

그런데 관계에 민감한 사회가 집단주의 문화권이다. 개인주의 문화권의 사람들보다 한국, 중국, 러시아, 일본 등과 같은 집단주의 문화권 사람들이 관계의 단절에서 오는 충격이 훨씬 더 크다.

### 지능과의 관계
자살과 관련 눈에 들어오는 상관관계가 하나 더 있다. 지능과의 관계다. 지능이 높은 지역일수록 자살률이 높다. 오스트리아 비엔나 대학의 의학과 마틴 보라섹은 85개 국가의 자살률과 지능을 포함한 다양한 지표와의 상관관계를 조사했다 (Voracek, 2004). 

지능이 높은 나라일수록 자살률이 높았지만, 그 나라의 부(GDP)와는 관계없었다. 왜 지능이 높을수록 자살 위험이 큰 것일까? 보라섹은 ‘자기희생’의 논리로 설명했다. 

한 개인이 더 이상 집단에 기여할 능력을 상실했다고 느낄 때 스스로를 기꺼이 희생한다는 설명이다. 일정 수준 이상의 지적 능력이 있어야 비관적 상황을 인지하고, 스스로의 생명을 중단시킬 결정을 내릴 수 있기 때문이다. 

생명은 한 개체만 살아남는다고 유지되는 게 아니다. 후손과 그 후손의 후손이 살아남아야 한다. 이처럼 진화의 관점에서 보면, 한 개인에게 중요한 것은 개체의 생명을 유지하는 것과 함께, 본인의 유전자를 후대에 남기는 것이다. 

이를 위해서는, 본인의 생명을 유지하기 위한 욕망 뿐 아니라, 그 자식의 자식이 살아 남도록 하는 욕망도 함께 있다. 양육이 바로 최상의 욕망이다(5장 욕망 참조). 

개체도 살고, 후손도 함께 잘 사는 상황이 바람직하겠지만, 만일 둘 중 하나를 선택해야 하는 상황도 생긴다. 이때, 사람들은 본인의 생명을 희생해서라도 자식과 함께 그 자식의 자식이 살아 남도록 돕는 선택을 한다. 

‘나’라는 개체는 사라져도 ‘나’의 유전자를 이어받은 ‘복제본’은 다음 세대로 계속 이어질 수 있기 때문이다. ‘나’는 죽어도 또 하나의 ‘나’는 살아남아, ‘나’의 또 다른 ‘생명’을 유지할 수 있게 된다.

이런 식으로 사람의 행동을 설명하는 이론이 포괄적 적합도(Inclusive Fitness)이론이다. 윌리엄 해밀튼이 1964년에 정립한 진화심리학의 근간이 되는 이론이다. 

가족이 왜 특별한지, 이타적 행위가 왜 이어지는지 등에 대한 설명에 유용하다. 해밀튼의 포괄적 적합도 이론은 리처드 도킨스의 이기적 유전자(Selfish gene)라는 도발적 제목의 책으로 널리 알려졌다 

:::{.callout-note}
주: 안타까운 일은 도킨스가 그의 책 제목을 ‘이기적’ 유전자라고 달았다는 데 있다. 도킨스의 의도는 유전자의 관점을 강조하기 위한 것이었지만, 무자비한 약육강식의 원리가 마치 진화론인 것 같은 오해를 강화시켰다. 이런 이유로, 도킨스는 대중의 비난과 동료 학자들의 힐난에 시달렸다. 도킨스는 <이기적 유전자> 30주년 판 서문에서 그의 책 제목에 대해 후회하는 내용을 포함시켰다. 책의 제목이 내용을 왜곡하는 경우가 많았기 때문이다. 도킨스는 ‘이기적’이란 수식어 대신 ‘불멸의’란 수식어가 더 나았을 것이라고 했다. 유전자는 스스로를 끊임없이 스스로를 복제해 나가는 일종의 ‘정보’이지, 이기적이지도 않고 이타적이지도 않기 때문이다. 이런 유전자의 작용이 개체 수준과 종의 수준에서 이뤄질 때 이타적 행동도 나타나고 이기적 행동도 나타난다. 
:::

### 이성 섹스의 영향 
일반적으로 개체의 생명과 유전자의 복제 사이에는 충돌을 일으키지 않는다. 개체가 살아 남아야, 유전자가 차세대로 복제될 수 있기 때문이다. 

그런데, 한 개인이 더 이상 재생산할 능력을 잃고, 소속 집단에 부담을 지운다고 느끼면 개인은 개체의 생명을 포기하는 선택을 하게 된다. 

캐나다 맥마스터 대학교 심리학과 데니스 디카탄자로는 포괄적적합도 이론으로 자살현상을 설명하기 위한 근거 자료를 제시했다. 캐나다 온타리오에 거주하는 일반인 522명 및 소외집단 (노인, 정신질환자, 수감자, 동성애자) 211명을 대상으로 자살을 시도했거나, 자살할 생각을 한적이 있는지에 대한 설문조사를 했다 (de Catanzaro, 1995).

설문 항목은 가족에 대한 부담, 가족과 사회에 대한 기여도, 성관계 빈도, 이성과의 관계의 안정성, 친밀도, 성공여부, 동성애, 친구의 수, 외로움, 다른 사람으로부터 받는 대우, 재정상태, 몸의 건강, 삶의 만족도, 미래에 대한 전망 등이었다. 

이 조사에서 자살과 가장 연관이 깊은 심리적 상태는 외로움과 가족 혹은 사회에 짐이 되고 있다는 부담감이었다. 일반인들과 정신질환자의 자살에 대한 생각 사이에는 별 차이가 없었다. 

자살과 큰 관계가 있는 항목이 성관계다. 성관계가 있으면 자살에 대한 생각이 크게 줄어든다. 빈도가 적을수록 자살 위험도가 높은 반면, 최근 한달 내에 성관계를 맺었으면 자살에 대한 생각이 크게 줄어든다. 이성과의 관계가 좋아도 자살 위험이 줄어든다. 이런 성향은 특히, 18세-30세 사이의 남성들에게서 두드러졌다. 

동성애 성향은 자살위험과 상관관계가 컸다. 남성 동성애자들의 응답도 흥미롭다. 다른 남자와 관계를 맺고 있음에도 여성 친구와의 관계가 나빠졌을 때 자살에 대한 생각을 더 많이 했다. 

이성과의 성관계에 대한 전망에 대해 남성과 여성 동성애자들의 응답이 반대로 나타났다. 남성 동성애자들의 자살생각은 감소했지만, 여성 동성애자들에게는 증가했다. 

이 연구는 자살을 유전자 관점에서 잘 설명해 준다. 본인의 유전자를 후대에 남기려는 가능성을 극대화하려는 선택이란 관점에서, 가족에 대한 부담, 가족과 사회에 대한 기여도, 및 성관계 빈도와 자살과의 관계를 잘 보여주고 있기 때문이다. 유전자의 관점에서 또 하나의 ‘나’를 지속적으로 이어가는 수단은 이성과의 성관계다. 

## 외로움의 고통
진화적 관점에서 자료를 분석하고 논의를 진행할 때, 주의해야 할 점은 사람의 선택이 의식의 영역에서 이뤄지는 게 아니란 데 있다. 가장 매력적인 여성의 힙과 허리의 비율에서, 사람들이 잘록한 허리를 보면서, ‘저 여성의 몸에서 태어날 아이들은 머리가 좋을 거야, 그러니까, 매력적이지’라고 하는 게 아니다 (4장 매력 참조).

직관적으로 ‘매력적이야’라고 느낀다. 자살이란 선택도 마찬가지다. 의식적으로 “자손을 생산할 기회가 사라졌고, 가족에게 부담을 지우니, 이 한 몸 희생해, 나의 유전자가 다음 세대로 이어가는데 부담을 주지 말아야겠다”라고 생각해 자살을 선택하는 게 아니다.

사람의 행동은 궁극적으로 개체의 생존과 종의 번식을 극대화 하는 방향에서 이뤄진다고 할 때, 사람들을 행동과 생각을 좌지우지하는 것은 즐거움과 고통의 감정경험이다. 

초콜렛 케익에 끌리는 이유는 몸에 필요한 에너지를 공급해야 한다는 의식적 생각에 따른 게 아니다. 케익의 달콤한 맛이 좋기 때문이다. 즐거움은 생존에 도움을 주니 ‘접근하라’는 신호 역할을 하고, 반대로 고통은 생존에 위협을 주니 ‘피하라’는 신호 역할을 한다. 

사람에게 가장 큰 고통을 주는 신호는 외로움이다. 외로움은 마음만 아픈 게 아니라 몸도 함께 아프게 하기 때문이다. 

### 실연증후군
실연하면 몸도 아프다. 소중한 사람을 잃었을 때 ‘가슴이 찢어지는 듯한 아픔’이라고 묘사한다. 영어권 사람들은 실연의 아픔을 부서진 심장 (Broken Heart)이라고 표현한다. 

과거에는 ‘가슴이 찢어지는 듯한 아픔’은 비유에 불과했다. 정서적으로 힘든 게 물리적인 가슴의 통증으로 이어지진 않을 것이라고 여긴 것이다. 

실연의 고통이 실제 물리적 고통을 수반하는 "진짜" 통증이다. “가슴이 저리다” 혹은 “마음이 아프다” 등의 표현은 비유 이상의 의미가 있다. 

미국 브라운대학 의학과 리처드 렉난테와 그 동료들은 2004년 7월부터 2008년 4월까지 미국 로드 아일랜드 주에 있는 두 병원의 다코스보 심근증 환자 70명에 대한 기록을 분석했다 (Regnante et al., 2008).

실연증후군(Broken Heart Syndrome)이라고 알려진 다코스보 심근증 (Takosubo Cardiomyopathy)은 혈관이 막힌 것도 아닌데 심장마비증세를 일으키는 병이다. 

심장 왼쪽 심실의 근육이 피를 원활하게 순환시키지 못하면서 심장마비와 비슷한 증세를 보인다. 느슨해진 심실의 모양이 문어잡이 항아리 모양을 해서, ‘다코스보 (문어잡이 항아리란 뜻의 일본어)’가 병명에 사용됐다. 

논문에 따르면, 환자의 37%가 정서적 원인, 33%가 물리적 원인, 30%는 원인불명의 스트레스 때문에 다코스보 심근증을 앓았다. 가장 많은 사례가 사람과 사람의 관계에서 비롯됐다. 가족에 대한 나쁜 소식이나 가족간 다툼이 각각 6건으로 주된 발병 원인이었다.

부모님을 양로원에 보낸 후 심장마비 증세를 보인 사람도 있다. 실직한 자식때문에 마음이 상해 '실연증후군'을 보인 경우도 있다. 중증 질환이나 이빨 뽑는 스트레스 등 물리적 고통때문에 '실연증후군'으로 고생한 사람도 있다. 정서적 고통과 물리적 고통이 동일한 증세의 심장질환을 일으켰다. 

사람들이 인간관계에서 오는 스트레스, 특히 정서적으로 친밀한 사람들과 헤어졌을 때 오는 스트레스를 가슴이 찢어지는 듯한 신체적 고통으로 경험하는 이유는 인간이 매우 극단적인 사회적 동물이기 때문이다. 

상호의존은 사회적 동물인 인간이 살아남는데 핵심요소다. 소속된 집단에서 떨어져 나가는 것은 곧 죽음이나 다름없다. 따돌림 연구 전문가인 퍼듀대학 심리학과 키플링 윌리엄스는 따돌림을 사회적 사형선고라고 묘사한다. 

사회적 동물에게 가장 큰 위협은 따돌림 당하는 것인데, 따돌림이 생존에 위협이 되는 위험 요소인 만큼 그에 상응하는 경보신호가 필요하다. 

### 통증, 고립 경보
신체적 통증이 바로 따돌림에 대한 경보 역할을 한다. 통증이 경보신호로 작용하려면, 문제의 심각성에 비례해 통증이 커야 한다. 정서적으로 친밀한 사람, 가족구성원의 상실은 심각한 문제 중의 하나다. 

가족이 될 연인도 가족만큼이나 끈끈한 정서적 유대가 형성돼 있다. 그런 구성원과 이별은 심각한 스트레스. 실연의 고통이 실제로 가슴 찢어지는 듯한 아픔으로 이어지는 까닭이다. 

스트레스에 취약한 사람은 그 경보신호 자체가 부담이 되기도 한다. 실연증후군은 바로 그런 사람들이 겪는 질환이다. 미국 로드아일랜드주의 경우, 실연증후군 환자의 95%가 폐경 이후 여성이었다. 

실연증후군에 대한 처방은 의외로 간단하다. 환자의 86%가 진통제나 진정제를 복용하고 퇴원했다. 심장에 물리적인 문제가 있기 때문에 생긴 병이 아니기 때문이다.

따돌림에 대한 뇌의 반응을 분석한 연구도 있다. 캘리포니아 주립대학(LA소재)의 나오미 아이젠버거 연구팀은 실험참가자들이 뇌영상장치인 fMRI안에 누워 ‘사이버볼’이란 게임을 하도록 했다. 

웹 브라우저에서 공을 주고 받을 수 있도록 게임이다. 브라우저를 열면, 게임캐릭터가 셋 나온다. 그 중 하나는 실험 참가자다. 게임이 시작되면, 마우스로 캐릭터를 클릭해 상대방에게 공을 던져주면 된다. 

공을 받은 캐릭터는 다시 공을 던져준다. 처음에는 세 캐릭터가 공을 주고 받지만, 중반부터는 두 캐릭터끼리만 공을 주고 받고, 실험참가자에게는 공을 던져 주지 않는다. 

둘이서 한 사람을 따돌리는 상황을 만들어 낸 것. 연구진은 이 때 따돌림 당하는 사람의 뇌가 어떻게 반응하는지 분석했다. 참가자들이 따돌림 당할 때, 등쪽 전대피질(Anterior Cingulate Cortex)이 활성화됐다. 

등쪽 전대피질은 경보시스템 역할을 하는 곳이다. 무엇인가 잘못되고 있다는 신호를 감지하는 곳이다. 통증을 느낄 때 활성화 된다. 즉, 따돌림 때문에 느끼는 불쾌함이 실질적인 통증이라는 것이다.
 
외로움은 개인이 사회에서 소외되고 있다는 신호다. 속한 집단에 기여할 수 있는 능력을 상실해 가고 있다고 느끼게 해주는 경보다. 일반적으로, 외로움을 느끼면, 이를 경보신호로 여기고 관계의 회복을 시도한다. 

그런데, 관계를 회복할 수 없다면? 외로움의 고통이 관계를 다시는 회복할 수 없다는 무력감과 남에게 부담스러운 존재가 된다는 자괴감과 겹칠 때, 개인은 희망을 잃고 스스로를 희생하려는 선택을 하려 한다. 

캐나다 몬트리올 대학의 아리엘 스트라빈스키와 리차드 보이어는 캐나다 퀘벡주 주민 1만9천724백명을 임의로 뽑아 설문조사했다 (응답률 79.9%). 외롭다고 느낄수록 자살을 시도했거나, 자살한 생각을 한 확률이 훨씬 높았다. 

외롭지 않다고 응답한 사람 중에 1.7%만이 자살할 생각을 한 적이 있다고 응답했다. 반면, 매우 외롭다고 응답한 사람 중엔 29.1%가 자살할 생각을 한 적이 있다고 했다.

### 자살은 지적인 선택
외로움이 자살이란 극단적 선택으로 이어지는 것은 인간 고유의 독특한 지적 능력과 관계가 깊다. 인류가 고도의 문화를 이룰 수 있었던 것은 인류만의 독특한 지적 능력 – 모의실험(Simulation)능력 – 이 있었기 때문이다. 

실제 경험해 보지 않고, 미래에 발생할 일을 마음 속으로 시뮬레이션해 봄으로써 시행착오를 극적으로 줄일 수 있었다 (Gilbert & Wilson, 2007). 초콜렛 푸딩은 마늘보다는 계피를 곁들여야 더 맛있다는 것을 알기 위해 굳이 초콜렛 푸딩에 마늘을 넣어보지 않아도 된다. 마늘이 어떤 맛을 낼지 마음 속으로 상상해볼 수 있기 때문이다. 

상상력 덕에 20만년 전 인류는 빙하기의 혹독한 가뭄 앞에서 멸종위기를 극복할 수 있었다. 먹을 것은 커녕 마실 물조차 제대로 구하기 힘든 상황에서, 호모 사피엔스는 그런 악조건을 "상상력"으로 극복해 냈다. 

물이 언제 필요할지, 어떻게 구할 수 있을지 예측하고 준비함으로써 혹독한 빙하기를 이겨냈다. 그런 과정에서 발달한 두뇌가 전전두엽이다. 

사람들은 전전두엽을 이용해 계획도 하고, 예측도 하고, 미래의 상황에 대한 시뮬레이션도 한다. 그런데, 바로 그 "상상력"때문에 인간은 행복하기도 하지만, 동시에 불행하기도 한다. 가지 사실에 너무 집착해, 그 특정한 경험을 부풀려 미래를 시뮬레이션 하는 경향이 있기 때문이다. 

예를 들어, 열차를 놓쳤던 경험이 있는 사람에게 미래에 열차를 놓치는 상황을 상상해보라고 하면, 최악의 경험을 떠올리는 경향이 있다. 그리고는 그 최악의 기억을 기반으로 미래에 겪을 고통을 시뮬레이션 한다. 미래의 고통이 실제보다 훨씬 부풀려지는 이유다 (Morewedge, Gilbert & Wilson 2005). 

미래의 감정적 상태를 예측한다고 해서 감정예측 (Affective forecasting)이라고 한다. 다니엘 길버트의 <행복에 걸려 넘어지다(Stumbling on happiness)>가 감정예측이란 심리현상을 통해, 어떻게 사람들이 불행해지는지 설명했다. 

미래를 예측하고 상상하고, 미래의 일을 미리 느껴볼 수 있는 능력이 미래를 준비하고 위험을 피하는데 커다란 도움이 됐지만, 종종, 바로 그 능력 때문에 오지도 않은 불행한 미래를 과도하게 걱정해, 모든 욕망을 상실해 버린다는 것이다.

## 심리적 면역
자살이란 현상은 포괄적 적응도와 감정예측이란 두 가지 틀에서 설명할 수 있다. 한 개인이 가족이나 사회에 기여하지 못하고, 단지 짐이 된다는 부담감을 갖게 될 때, 외로움 혹은 우울증이란 경보신호가 울린다. 

이 경보신호를 과도하게 해석해 영원히 가족과 사회에서 소외될 것으로 부풀려 받아들일 때, 스스로의 목숨을 끊은 극단적 선택을 하게 된다고 할 수 있다. 

이 접근은 21세기 초엽 한국사회에 자살이 크게 늘고 있는지에 대한 좋은 설명이 된다. 한국사회는 일본제국주의의 45년간의 식민지배를 통해 지구 상에서 가장 못사는 나라로 전락했지만, 불과 반세기 만에 세계 10대 경제대국을 바라볼 수 있을 만큼 빠르게 성장했다.

한국인의 우수성일 수도 있지만, 피땀 흘려 노력한 결과다. 그 대가가 있다. 한국사회가 세계에서 가장 치열한 경쟁터가 되고 말았다. 

부와 능력이 다른 가치를 우선하는 문화가 형성됐다. 능력 중심의 경쟁문화는 승자대열에 끼지 못한 구성원들이 박탈감을 심하게 느끼게 한다. 

승자 역시 경쟁문화의 그늘에서 자유롭지 못하다. 승리의 단맛은 영원한 게 아니기 때문이다. 내부와 외부의 지속적인 도전에 언젠가는 반드시 승자의 자리를 내줘야 한다. 

그 박탈감에서 오는 고통은 애초에 승자가 되지 아니한 만 못할 만큼 고통스럽다. 유명 연예인들이나 성공한 기업가의 갑작스러운 자살이 드물지 않은 까닭이다.

경쟁문화가 팽배한 한국사회에서 자살은 피할 수 없는 운명과 같은 것일까? 그렇지는 않다. 다니엘 길버트는 그의 책 제목을 <행복에 걸려 비틀거리다(Stumbling on Happiness>라고 했다. 

영어 단어 ‘Stumble’의 사전적 뜻은 무언가에 걸려 비틀거리는 것이지만, 그 안에 내포한 뜻은 "의도하지 않게 무엇인가에 엮인다"는 내용도 있다. 아무리 좋지 않은 일에 엮이더라도, 사람은 늘 적응(adaptation)한다는 것이다. 

적응이라는 본능적인 심리기제가 작동하면, 아무리 불행한 일을 당해도 스스로 행복해질 수 있다. 이런 이유로 심리학자들인 <행복에 걸려 비틀거리다> 역자들이 Stumble을 의역하지 않고, "비틀거리다"라고 직역한 게 책의 본 뜻을 훨씬 제대로 전하고 있다.

길버트는 이런 적응의 심리기제를 심리적 면역체계라고 했다. 어떠한 곤경이라도 적응하는 무의식작용이다. 흥미로운 점은 현실상황에 대한 선택의 여지가 없을 때 심리적 면역체계가 더 잘 작동한다는 사실이다. 어쩔 수 없이 적응해야 하기 때문이다. 

어떤 비극적 현실에 얽매여 선택의 여지가 없을 때라도, 바로 그 부정적 현실이라는 돌부리에 걸려 비틀거릴 때, 그 돌부리는 피할 수 없는 우리의 현실이 되고 만다. 우리를 비틀거리게 하는 현실이다. 

그런데, 바로 그 현실에 엮이게 되고, 적응하면서 행복을 합성해 낸다. 역경이란 돌부리에 걸려 비틀거릴 때, 적응이라는 심리적 면역체계가 작동하는데, 도움이 되는 조건이 있다. 

바로 삶의 의미다. 그런데, 삶의 의미는 사회적 관계에서 온다. 사회에 짐이 되고 있다는 부담감이 자살을 생각하게 하는데, 바로 그 사회적 관계가 자살을 막을 수 있는 유력한 원천이라는 사실은 묘한 역설이다.

