# 선택

## 자유의지는 환상인가?

과거로 돌아간다면 사람들은 과연 다른 선택을 할 수 있을까? "내"가 어떤 행동을 하는 이유는 나 자신이 그렇게 생겨먹었기 때문이라고 할 수 있다. 부모로부터 물려받은 유전자는 나의 성품과 기질을 결정하고, 내가 자란 환경은 나의 성품과 기질이 특정한 식으로 발현되도록 한다. 모든 게 유전자와 환경에 의해 정해졌다면, “내”겐 선택의 여지 따위는 없어 보인다. 아무리 과거로 여러번 돌아가 봐야 똑같은 선택을 할 수 밖에 없을 듯 하다. 마치 운명이 모든 것을 결정해 놓은 것처럼 말이다. 
인류는 '운명의 힘'을 음악으로, 시로, 영화로 다양하게 표현했다. 베르디의 오페라 <운명의 힘(La Forza Del Destino)>도 그 중 하나. 아버지가 반대하는 결혼을 하려다, 아버지를 죽게하고, 친오빠에 의해 죽임을 당하는 레오노라의 슬픈 운명을 그렸다. <운명의 힘> 서곡의 주제가 나오는 영화 <마농의 샘> 역시 운명에 짓눌린 슬픈 인생을 그리고 있다. 도시에서 세무사를 하던 쟝이 농사를 짓기 위해 고향으로 돌아왔을 때 그를 기다리고 있던 것은 죽음이라는 운명이었다. 그의 땅과 물을 탐낸 빠뻬와 위골랭의 계략과 음모 때문이다.  빠뻬와 위골랭 역시 그의 탐욕때문에 비참한 운명을 맞이한다. 위골랭은 그가 파멸한 쟝의 딸 마농에게 반한다. 위골랭은 마농의 마음을 사기 위해 짐승을 잡아 마농에게 주지만, 마농은 마음을 주지 않는다. 위골랭은 조금씩 커다란 짐승을 잡아 주는데, 결국은 가장 큰 짐승(위골랭 본인의 목숨)을 마농에게 바치고 만다. 빠뻬 역시 비참하게 생을 마감한다. 그가 죽음에 내몬 쟝이 바로 그의 친아들이었기 때문이다. 
호머의 대서사시 <일리어드> 역시 운명의 힘에 끌려 살아가는 영웅들의 이야기다. 영웅들은 무용과 지혜를 뽐내지만, 이들의 행동은 자유의지에 따른 의식적 선택보다는 신들에 의해 짊어진 운명에 끌려다닌다. 헥토르가 아킬레스의 절친한 친구 파트로클루스를 죽이고, 헥토르는 다시 아킬레스에 의해 죽임을 당하고, 이 때문에 아킬레스는 파리스의 화살이 맞아 죽는다. 신이 정한 운명대로 말이다. 
(그림: 피터 폴 루벤스의 그림은 <일리어드>의 장면을 묘사한 <아킬레스 헥토르를 죽이다>이다. 영화 <트로이>에서도 아킬레스와 헥토르의 전투장면을 실감나게 그렸지만, 루벤스는 운명의 힘을 잘 묘사하고 있다.)
사람에게는 의식하지 못하는 마음의 작용이 있는게 분명해 보인다. 의식적인 통제 바깥에서 자동적으로 작동한다고 해서 ‘자동처리’라고 한다. 오랜 세월 인류가 운명의 힘을 이야기해 온 것은 우연이 아니다. 운명이란 것이 신과 같은 초월적 존재가 미리 결정해 놓은 것은 아닐 지라도, 사람이 의식하지 못하는 힘이 있다. 누구의 피를 물려받았는지에 따라 기질과 성품이 결정되고, 어느 장소에, 어느 시기에 태어났냐에 따라, 그 기질과 성품의 발현이 결정된다. 
‘지름신이 내렸다’는 표현이 있다. 당초 구매할 의도가 없었는데도, 꼭 필요한 게 아님에도 순간 무엇인가에 홀린 듯이 ‘질러’버린다고 해서 ‘지름신’이라고 한다. 분명히 나의 손과 나의 의지로 구매한 것인데, “내 정신이 아니었던 것”이라 할 수 있다. ‘나’의 행동이 반드시 ‘나의 의지’에 따른 선택이 아닌 현상은 반드시 상품 구매에 국한되지 않는다. 이런 이유로 자유의지라는 것은 아예 존재하지 않는다는 주장도 있다. 개인은 각자의 선호도에 따라 선택하는데, 선호도는 유전자와 환경이 결정하기 때문이란 것이다. 영국의 리딩대학 철학과 캘런 스트로슨의 논리는 명쾌하다.

(1)	내가 하는 어떤 행동을 하는 이유는 내가 그렇게 생겨먹었기 때문이다. 내가 아침에 시리얼을 먹길 원한다면, 내가 아침식사로 시리얼을 선호하기 때문이다. 
(2)	내가 나의 선택에 책임을 진다면, 내가 생겨먹은 것에 대한 책임이 있다고 하는 것이다.
(3)	그러나, 나는 내가 생겨먹은 것에 대해서는 책임이 없다. 어느 순간, 나의 욕구와 필요가 나의 선호도를 결정하는데, 이는 내가 통제할 수 있는 게 아니다. 나의 욕구와 선호도는 자연선택에 의해 결정됐고, 이는 나의 유전자에 각인돼 있다. 또한 욕구와 선호도는 나의 부모, 형제, 친구 및 환경에 의해 영향 받는다.
(4)	고로, 나는 궁극적으로 나의 선택에 책임이 없다. 나의 선호도는 나와는 관계없는 수백만가지 요소가 결정한다. 내가 나 자신의 행동의 원인이 될 수 없다.
(5)	내가 나의 행동에 책임이 있는 것은 내가 나의 의지가 나의 행동의 원인이 됐기 때문이 아니다. 원인은 나의 유전자와 나의 환경이다. 나의 행동에 내가 책임을 저야 하는 까닭은 내가 나의 몸과 행동에 대한 소유자이기 때문이다 (Strawson, 2010).

논리는 정교한데 정서적으로 잘 와 닿지 않는다면, 일상생활으로 돌아와 보자. TV는 현대인의 일상에 중요한 부분을 차지한다. 수십 개가 넘는 채널을 통해 다양한 프로그램이 제공된다. 스릴과 흥분을 만끽할 수 있는 각종 스포츠프로그램과 액션영화부터, 조용한 음악회나 자연을 주제로 한 다큐멘타리까지 다양하다. TV채널을 돌리면서, 어느 프로그램을 선택할지는 리모콘을 쥔 사람이 어느 채널 버튼을 누르냐에 달려있는 것처럼 보인다. ‘내’가 보고 싶어 선택한 것이기 때문이다. 미국 알라바마 대학의 제닝스 브라이언트와 돌프 질만은 TV선택이 반드시 개인의 의식적인 선택의 결과가 아닐 수 있다는 근거를 제시했다. 브라이언트와 질만은 우선 참가자들을 두 집단으로 나눴다. 한 집단은 어려운 시험문제를 20분 동안 집중적으로 풀도록 해, 긴장과 스트레스를 유발했다. 다른 한 집단은 아주 단순한 과제를 20분 동안 반복하도록 해 지루함을 느끼도록 했다. 그리고는 TV프로그램을 자유롭게 보도록 했다. TV프로그램은 미식축구나 액션영화 등 자극적인 프로그램과 클래식 음악회나 자연 다큐멘타리 등 안정을 취하도록 하는 프로그램 두 종류였다. 실험 참가자들이 리모콘으로 TV프로그램을 자유롭게 선택하는 동안, 어떤 프로그램을 선택했는지 분석했다. 지루한 조건의 참가자들은 대부분의 시간을 스포츠나 액션영화처럼 자극적인 프로그램에 할애했다. 반면, 스트레스 조건의 참가들은 클래식음악회나 자연다큐멘타리에도 스포츠나 액션영화 못지 않은 시간을 할애했다. TV시청 후에는 왜 선택한 프로그램을 보았는지 물었다. 참가자들은 다양한 이유를 들었지만, 참가자들은 그들의 선택의 원인으로 흥분과 지루함을 지목하지는 못했다. 언뜻 ‘나’의 의지로 액션영화도 선택하고, 음악회를 선택하는 것처럼 보이지만, 실은 의식하지 못하는 개인의 욕구(긴장감 혹은 따분함의 해소)를 충족한 결과였다는 것이다.
아직도 자유의지에 ‘미련’이 간다면, 월드컵 기간을 떠올려 보자. 한국인 대부분은 아마도 월드컵 기간에 한국팀의 승리에 기뻐하면서도, 일본 팀의 승리에는 시큰둥했다. 한국팀과 일본팀에 대한 선호도가 분명하기 때문이다. 그런데, 그 선호도는 “내”가 한국사람이라는 이유때문이지, 한국팀과 일본팀 사이에 어떤 의미 있는 차이점이 있기 때문이 아니다. 즉, 단지 ‘나’에게 한국인의 피가 흐르고, 한국이라는 환경에서 살기 때문에 한국팀에 대한 강한 선호도가 형성된 것이다. ‘나’의 한국팀 선호도는 ‘나’의 의지에 따른 결과가 아니란 것이다. 여전히 “자유의지는 없다”는 주장에 불편하다면 다음의 고전적인 사회심리학 연구결과를 보자.
1954년 미국 오클라호마 로버스 케이브 주립공원에 22명의 11세 소년들이 여름캠프에 모였다 (Sherif et al., 1961). 미국 오클라호마 대학 무자퍼 쉐리프 연구팀의 집단갈등 실험에 참가하기 위해서였다. 캠프장에 도착하기 전, 소년들은 임의로 두 집단으로 나뉘었다. 첫 일주일 동안 두 집단의 소년들은 각각 다른 곳에 캠프를 차렸다. 수영도 하고 하이킹도 하면서 집단에 대한 정체성을 만들어 갔다. 일주일이 지나자 소년들은 그룹 이름도 짓고, 그룹명을 깃발과 셔츠에 찍었다. 한 집단은 래틀러였고, 또 한 집단은 이글스였다 (관련 사진: http://psychclassics.yorku.ca/Sherif/chap4.htm). 래틀러와 이글스는 서로의 존재에 대해서는 알지 못하고 있었다. 래틀러와 이글스의 집단 정체성이 형성된 다음, 쉐리프는 두 집단이 조우하도록 했다. 두 집단의 반목이 감지됐다. 쉐리프는 두 집단 사이에 경쟁을 붙였다. 텐트치기 시합이나 야구와 같은 경기를 하게 했다. 래틀러와 이글스의 반목이 더욱 더 심해졌다. 급기야, 두 집단의 소년들은 서로에 대해 비난하기 시작했다. 심지어, 같은 방에서 식사하기도 거부했다.
쉐리프의 실험은 의도대로 진행됐다. 1단계에서 집단 정체성이 형성됐고, 2단계에서는 집단간의 갈등과 편견이 생겼다. 마직막 3단계(갈등의 해소단계)로 접어들었다. 래틀러와 이글스를 화해하도록 하기 위해 두 집단이 오락활동을 함께 하도록했다. 영화를 함께 보게 했지만, 두 집단의 갈등은 해소되지 않았다. 쉐리프는 새로운 방식을 시도했다. 래틀스와 이글스를 새로운 장소로 이동시킨 뒤, 풀기 어려운 과제를 제시했다. 캠프장에 공급되는 물탱크의 물꼭지를 막은 다음 커다란 돌로 막아 놓았다. 실험 운영진에게 비난이 돌아가지 않도록, 소년들에게는 외부인의 소행이라고 했다. 두 집단의 소년들은 물꼭지를 수리하기 위해 협력했다. 함께 문제를 해결한 이후, 소년들은 서로 어울리기 시작했다. 식사도 함께 하고, 같은 버스를 타고 집에 돌아왔다. 
래틀러와 이글스의 소년들이 서로 반목했던 것은 그들의 소속때문이었다. 그런데, 래틀러가 될지, 이글스가 될지는 소년들이 결정한게 아니었다. 쉐리프의 실험스탭들이 임의로 나눈 것이다. 한 순간 래틀러에 속했기 때문에, 이글스에 속한 소년들이 밉고 싫었던 것이다. 그런데, 그렇게도 서로를 미워하고 싫어했던 소년들이 공동의 과제를 함께 해결하면서 사이가 좋아졌다. 소년들이 서로를 싫어했다, 좋아했던 것은 쉐리프가 설정한 의도 그대로 였다. 소년들이 ‘자유의지’에 따라 선택해서 서로 반목하고 화해한 게 아니었다. 쉐리프 연구팀이 설정한 상황이 그렇게 만들었다.   

## 상황의 힘
상황의 힘을 보여주는 보다 유명한 사회심리실험은 스탠포드 감옥실험이다 (Zimbardo, 2004). 스탠포드 감옥실험은 실제상황을 그대로 모방하면서 시작됐다. 평범한 대학생들은 간수와 죄수 두 집단으로 나뉘었다. 죄수 역할을 맡은 학생들은 실제 상황과 같은 방식으로 실험실 감옥에 갖혔다. 경찰 복장을 한 운영진에 의해 체포돼, 스탠포드 대학 지하에 마련된 감옥으로 이송됐다. 지문 찍고, 눈을 가린 채 각자의 수용실로 보내졌다. 옷을 다 벗긴채로 수색 당했고, 소독되고, 삭발 당하고, 죄수복을 입은 다음, 죄수번호를 받고, 한쪽 발에는 사슬이 채워졌다. 간수 역할을 맡은 학생들은 간수복을 입고 곤봉을 지급받았다. 실험 첫날은 조용하게 지나갔다. 둘째 날, 죄수역할을 맡은 학생들이 그들의 처우에 반발했다. 간수 역할을 맡은 학생들은 즉각 보복했다. 죄수들의 옷을 벗기고, 수용실에서 침대를 없앴다. 주모자는 독방에 가두었고, 죄수 역할을 맡은 학생들을 못살게 굴었다. 단 이틀만에, 죄수 역할을 맡은 학생들은 간수의 명령에 순종하는 죄수가 됐다. 명문 스탠포드 대학교 학생이란 정체성은 죄수번호가 지워버렸다. 간수 역할을 맡은 학생들도 마찬가지였다. 그들은 엄격하고 권위적인 간수가 됐다. 평화주의자였던 젊은이들이 간수의 역할을 맡게 되자, 죄수 역할을 한 동료학생들을 욕되게 하고 신체적으로도 가혹행위를 했다. 심지어 이를 즐기기까지 했다. 실험을 주관한 짐바르도 교수 자신도 실험상황에 빠져들었다. 그의 실험참가자들의 안녕보다는 감옥의 보안에 보다 더 신경쓰게 됐다. 당초 이 실험은 14일동안 지속돼기로 했지만, 6일만에 끝내야 했다. 주어진 역할이 사람을 어떻게 극적으로 바꾸어 놓는지 보여준 사례다. 
스탠리 밀그램도 복종 실험을 통해 상황의 힘이 얼마나 강력한지 보여 주었다 (Milgram, 1963). 밀그램은 학습실험이라고 소개하면서 사람들을 그의 실험실로 초대했다 (그림: http://en.wikipedia.org/wiki/Milgram_experiment). 실험참가자들의 역할은 학습자에게 전기충격을 가하는 것이었다. 전기충격기라고 소개된 기계에는 전기 볼트가 적혀 있는 스위치들이 있었다. 순차적으로 강력한 전기충격을 줄수 있는 것처럼 보였다. 마지막 세번째 스위치에는 “위험: 심한 충격”이라고 표기됐다. 마지막 두개는 “XXX”라고만 표기했다. 학습자가 실수하면 실험참가자들은 전기 스위치를 조작해 전기충격을 가하도록 지시를 받았다. 학습자들은 사전 각본대로 계속 실수했다. 전기충격 스위치를 올릴 때 마다 학습자들은 각본대로 고통을 호소했다. 물론, 실제로 전기충격이 가해진 것은 아니었다. 사정을 모르는 실험 참가자들은 그들이 학습자들에게 고통을 안겨준다고 믿었다. 실험참가자들은 점점 전기충격의 수위를 높여가도록 지시받았다. 학습자들이 비명 지르며 중단할 것을 요구했지만, 실험참가자들의 63%가 지시대로 마지막 스위치까지 올렸다. 학습자가 죽을지 모르는데도 말이다.
상황의 힘은 일상에서도 종종 나타난다. 앞서 예로 든 ‘지름신이 내렸다’고 하는 충동구매가 좋은 예다. 상황의 힘을 보여준 일련의 심리학 실험은 인간에게 선택이란 무엇인지, 자유의지는 환상이 아닌지 생각하게 만든다. 로버스 케이브 공원실험에서 보여준 래틀러와 이글즈의 반목은 자유의지의 결과일까? 처음부터 래틀러와 이글즈가 공동의 과제를 풀도록 했다면 소년들이 반목했을까? 실험참가 학생들은 실험기획자의 의도대로 반목하기도 하고, 화해하기도 했다. 스탠포드 대학 지하에 마련됐던 감옥에서 벌어진 일 역시 사람의 행동에 외적 요인의 영향력이 크다는 점을 보여준다. 평화주의자였던 대학생들은 주어진 상화에 따라 동료 학생들을 학대했다. 과연 스탠포드대학교의 학생들은 자유의지로 동료학생들을 학대한 것일까? 밀그램의 복종실험에 참여했던 사람들의 가학행위에 대해서도 같은 질문을 던질 수 있다. 이들이 전기충격을 가한 것을 자유의지에 따른 행동이라 할수 있을까? 아니면, 단지 상황이 강제한 것일 뿐인가?  <설득의 심리학>으로 유명한 로버트 치알디니는 이런 상황의 힘을 6가지로 요약했다 (주: 6가지 설득의 심리: 무엇인가 빚진 것을 갚고 싶다는 상호성, 이미 저지른 일에 대해 일관성을 유지하고 하는 심리, 대부분의 사람들이 하고 있다는 사회적 증거, 권위에의 복종, 사람과의 관계에서 호감, 그리고 기회가 사라질지도 모른다는 희소성). 그의 베스트셀러 <설득의 심리학(Influence: Science and Practice)>은 이 여섯가지 원리를 정리한 책이다. 선택은 개인이 자유의지로 무엇인가를 결정하는 게 아니라, 여러 상황적 조건이 개인의 본성과 복합적으로 상호작용한 결과다.

## 상황의 내면화
인간 행동에 대한 상황의 힘의 연구에서 주목해야 할 부분이 내면화다. 실제로는 상황의 힘에 의한 행동이라도, 의식의 영역에서는 스스로의 선택 혹은 자유의지의 결과라고 여기는 경향이 있다. 레온 페싱어와 메릴 칼스미스의 인지부조화 실험은 상황의 힘이 어떻게 내면화하는지 보여주는 좋은 사례다 (Festinger. & Carlsmith 1959). 실험에 참가한 학생들은 우선 실패 돌리기 등과 같은 아주 단순한 과제를 한시간동안 해야했다. 지루함과 따분함에 몸서리쳤을 학생들에게 한가지 부탁을 했다. 다른 실험참가자들에게 그 지루했던 과제가 “정말로 재미있었다”고 말해달라는 것이었다. 그리고는 1달러를 그 대가로 제공했다. 다른 그룹의 실험참가자에게도 똑 같은 부탁을 하면서 20달러를 제공했다. 요즘 물가로 따지면 20만원쯤 된다. 마지막으로 실험참가자들에게 그 따분했던 과제가 얼마나 흥미로웠는지 물었다. 20달러를 받은 학생들은 “재미없었다”고 답했다. 반면, 1달러를 받은 학생들은 그 지루했던 실패돌리기를 “재미있었다”고 답했다. 페싱어와 칼스미스는 이를 인지부조화로 설명했다. 20달러는 사소한 거짓말에 대한 충분한 보상이 되겠지만, 1달러는 그렇지 못하다. 즉, 20달러 받은 학생들은 거짓말에 대한 충분한 보상를 제공받았다고 생각하면 그만이다. 그런데, 1달러는 거짓말한 것에 대한 충분한 보상이 되지 못한다. “난 정직한 사람이다”라는 믿음과 “다른 사람에게 거짓말을 했다”라는 생각사이에 부조화가 발생한다. 이미 저지른 행동과 태도 사이에서 바꿀 수 있는 것은 객과적인 상황 (이미 저지른 행동)이 아니라 주관적인 상태(태도)다. 인지부조화라는 불편한 상황을 해소하기 위해서는 “정말로 재미있었다”고 태도를 바꾸는 방법 밖에 없다 (주: 자아지각, 제약만족모형 등 인지부조화에 대한 다양한 대안이 제시됐지만, 생리과학 및 신경과학의 연구 결과는 기존의 페싱어의 인지부조화와 일치한다 (Harmon-Jones, & Harmon-Jones (2008)).
실험참가자들이 그 따분했던 실패 돌리기를 “재미있다”고 한 것은 자유의지에 의한 선택이라고 할 수 있을까? 제3자의 시각에서는 상황이 그렇게 만든 것이라고 여길 수 있다. 그렇지만, 태도를 바꾼 당사자의 입장에서는 분명히 자유의지에 따른 자율적인 선택일 수 밖에 없다. 스스로의 선택에 의한 태도변화라고 여기지 않는다면 인지부조화가 해결되지 않기 때문이다. 자유의지에 대한 논의가 쉽지 않은 이유가 바로 여기에 있다. 상황의 힘에 의해 이뤄진 어쩔 수 없는 선택이지만, 실제 개인은 자유의지에 따른 자율적인 선택이라고 확신하기 때문이다. 

## 자유의지란 환상
사람들이 의식적으로 인지하는 자유의지는 진정한 의미의 자유의지가 아니라 자유의지가 있다고 느끼는 환상이다. 그러나, 자유의지가 환상이라는 주장은 쉽게 받아들이기 어렵다. 인간에게 자유의지가 있다는 것은 너무나 명백해 보이기 때문이다. 내 손가락을 내가 움직이는데, 나의 자유의지에 따른게 아닐 수 있다니 말이다. 그렇다면, 내가 하고 싶어 하는 것들이 “내” 의지가 아닐 수 있다는 것은 도대체 무슨 말이란 말인가? 그렇지만, 잠시만 마음을 열어보자. 1983년 벤자민 리벳과 그의 동료들의 연구는 일반적으로 알고 있는 자유의지가 환상임을 보여주는 좋은 예다 (Libet, et al., 1983). 손가락을 들어 올리겠다는 느낌이 들기 이전에 이미 뇌는 손가락을 들어 올릴 준비를 하고 있었다는 연구다. 리벳은 실험참가자들에게 손가락을 들어 올리라고 하면서, 뇌파를 EEG(Electroencephalogram)측정했다. 실험참가자들에게는 언제 손가락을 들어 올리려고 했는지 물었다. 실험참가자들은 손가락을 들어 올리기 0.2초전에 올리려는 의식적 판단을 했다고 답했다. 그런데, 뇌파를 통해 나타는 두뇌는 이미 약 0.5초전부터 손가락을 들어 올리려는 준비를 하고 있었다. 실험참가자들이 손가락을 움직이겠다고 생각한지 0.3초전에 이미 두뇌는 움직임을 준비하고 있었던 것이다. 
최근의 독일 막스플랑크 연구소 헤이네스팀의 실험에서는 두뇌가 의식보다 10초나 먼저 손가락의 움직임을 준비하고 있다는 근거를 제시했다 (Soon, et al. 2008). 연구팀은 실험참가자에게 두 손에 버튼 하나씩을 쥐고서 본인의 선택에 따라 버튼 하나를 누르게 했다. 동시에 실험참가자들의 뇌에서 일어나는 반응을 뇌영상장치(fMRI)을 통해 관찰했다. 실험참가자들이 ‘내가 어떤 버튼을 누를지 결정했다’고 생각하며 버튼을 누른 순간보다 10초나 먼저 손가락의 움직임을 관장하는 뇌 부위에서 신경 반응이 나타났다. 위의 두 실험은 우리가 자유의지에 따라 어떤 결정을 내렸다고 생각하는 시점은 이미 뇌에서 그 결정과 관련한 활동을 준비한 다음임을 보여준다. 이미 두뇌가 모든 일을 다 준비해 놓은 다음, ‘나’는 실제 실행하기 직전에 그 행동에 대한 의도를 추론해 낸다는 것이다 (Wegner & Wheatley 1999). 즉, ‘나’의 의도가 직접적으로 ‘나’의 행동을 일으키게 한 것은 아니지만, ‘나’의 행동이 ‘나’의 의도에 의한 것이라고 인식하게 된다는 것. 이런 점에서 우리가 알고 있는 자유의지는 환상이라고 할 수 있다. 그럼에도 자유의지란 환상이 필요한 이유는 내 몸을 내가 통제하고 있다는 느낌(sense of agency)이 필요하기 때문이다. 내가 손가락을 움직이려고 의도했는데, 그 시점에서 10초 후에 손가락이 움직인다고 하면 어떤 느낌이 들까? 손가락을 움직이겠다고 생각하고, 2초 후에는 발가락을, 5초 후에는 입술을, 9초 후엔 머리를 움직이겠다고 의도한 상황을 가정해 보자. 내 몸이 내 뜻대로 움직이는 게 아니라, 제멋대로 움직인다는 느낌이 들것이다. 머리를 움직이겠다고 의도했는데, 곧바로 움직이는 것은 머리가 아닌, 손가락일 테니 말이다. 움직이겠다고 생각한지 곧바로 (0.2초 정도) 손가락이 움직여 줘야, 내가 내 동작을 통제하고 있다는 느낌이 든다.

## 의식의 역할
자유의지가 환상이라면, 의식은 인간에게 무슨 의미가 있을까? 우선 사람의 마음이 어떻게 작동하는지 짚어봐야 한다. 1장에서 논의한 대로 사람의 마음은 크게 자동과정과 통제과정 두가지로 구분할 수 있다. 자동과정은 말 그대로 의식의 통제가 필요 없이 자동적으로 이뤄지는 마음의 작용이다. 사람의 마음에 자동과정이 반드시 필요한 이유는 우리가 사는 세상이 너무나 복잡하기 때문이다. 단순해 보이는 손가락 하나의 움직임도 실은 대단히 복잡한 과정을 거친다. 손가락 하나 움직일 때, 이와 관련된 세세한 작용 하나 하나를 모두 의식적으로 통제하는 것은 낭비다. 이는 기업의 CEO가 직원들의 일상적인 업무를 일일이 결재 받도록 하는 것과 같다. 일상적인 업무는 직원들이 알아서 하도록 하고, CEO는 조율이 필요한 의사결정만 내리는 게 정상적인 회사다. 사람의 마음도 마찬가지다. 기업에 생산, 영업, 관리 등을 담당하는 부서가 따로 있듯, 사람의 마음도 특정한 기능을 위한 “부서”가 존재한다. 각각의 마음의 부서는 고유의 영역에서 의식의 통제없이 자동적으로 돌아간다. 일상적인 업무는 CEO의 직접적인 지시없이 자율적으로 돌아가듯 말이다. 의식이 관여하지 않아 ‘무의식’이라고 하고, ‘자동과정’이라고도 한다. 
무의식이 자유의지에 관여하는 이유는 의식이 "값비싼 자원"이기 때문이다. 사소한 것까지 의식이 관여한다면 정작 중요한 작업을 제대로 수행할 수 없다. 고액 연봉을 받는 CEO가 사소한 일을 모두 챙기지 않는 것과 같다. 손가락하나 움직이는데 10초 동안 생각하고 있다는 것은 대단히 비효율적이다. 사람이 뇌를 10%만 사용한다는 말이 있는데, 이는 틀린 말이다. 두뇌가 신경전달물질을 재활용 한다는 점을 고려하면 110%까지 활용한다 해도 과언이 아니다. 하지만 인간의 의식이 차지하는 비중이 뇌 활용의 10%라고 한다면 그렇게 틀린 말은 아니다. 그만큼 무의식적인 작용의 비중이 크다는 것이다. 흔히 자유의지라고 생각하고 여기고 있던 것조차 무의식의 영역이 관여할 정도이니 말이다.
대부분 마음의 작용이 자동으로 이뤄진다면, 의식은 도대체 무슨 일을 하는 것일까? 의식의 기능은 기업의 CEO처럼, 생각, 느낌 및 행동을 높은 수준에서 조율하는 일이다 (Bargh, 2005). 몽유병 환자는 수면중 잠자리에서 일어나 일상적인 과제를 무리없이 수행해 낸다. 심지어 자동차를 운전하는 복잡한 과제도 거뜬히 수행해 낸다. 그런데, 의식이 없기 때문에 사고를 일으킬 위험이 높다. 행동이 의식의 조율을 받지 않기 때문이다. 이 대목에서 우리는 진정한 의미의 자유의지를 찾아낼 수 있다. 1장에서 사람의 마음은 말과 마부와의 관계에 비유했다. 말이 자동과정 혹은 무의식이라면, 마부는 통제과정 혹은 의식이라 할 수 있다. 마부는 말의 움직임을 직접적으로 통제하지 않는다. 마부가 말을 잘 부리기 위해서는 말과 교감이 이뤄져야 한다. 말의 상태를 잘 파악하면서, 마부의 신호를 말이 제대로 이해할 수 있도록 평소에 잘 훈련시키야 한다. 진정한 의미의 자유의지는 마부가 말을 부리는 기술을 습득해 가는 과정에 비유할 수 있다. 말은 마음의 작용에서 자동처리과정에 대한 비유다. 말을 부리는 기술을 습득한다는 비유는 자동처리과정을 만들어 가는 것이라고 할 수 있다. 의도적으로 좋은 습관을 만드는 게 좋은 예다. 의식은 값비싼 자원이기 때문에 마음껏 쓸 수 없다. 쉽게 고갈된다. 따라서 의식이란 자원이 고갈되지 않기 위해서는, 가능하면 의식이 관여 없이 무엇인가를 하도록 해야 한다. 습관이란 것은 의식의 관여 없이 특정한 일을 하는 것이다. 그런데, 사람은 의식적으로 특정한 습관을 만들 수 있다. 일단 습관이 형성되면, 의식은 더 이상 관여하지 않아도 된다. 이런 점에서 사람이 의식을 갖게 된 것은 무의식의 영역에서 자동적으로 작동하는 다양한 마음의 작용을 조합해 내기 위한 것이라고도 할 수 있다. 마음의 훈련이 진정한 의미의 자유의지인 셈이다. 자유의지를 통해, 자유의지가 작동하지 않는 자동, 혹은 무의식의 영역을 만들어 낸다는 게 조금은 역설적이긴 하지만 말이다.
