# 교육

## 성공의 비밀은 기개

미국 뉴욕시의 허드슨 강을 따라 북쪽으로 80km정도 가면, 웨스트 포인트로 알려진 미국육군사관학교가 있다. 웨스트 포인트는 2009년는 포브스지에서 선정하는 미국 최고의 대학에 아이비리그 대학들을 제치고 1위에 선정됐다. 2010년에는 4위였다. 그만큼 웨스트 포인트 입학 경쟁은 여느 일류대학 못지 않게 치열하다. 입학 원서를 넣으려면 우선 의회나 육군성의 구성원으로부터 추천을 받아야 한다. 웨스트 포인트는 자체적으로 개발한 총합후보척도(WCS: Whole Candidate Score)를 이용해 신입생을 선발한다. WCS는 학력과 지능평가인 SAT점수와 내신성적, 리더십 역량 및 체력 등을 종합한 척도다. SAT가 가장 큰 비중을 차지하지만, 학생회장, 스포츠 팀 대표, 교내언론 편집장 등 리더십 비중도 적지 않다. 대체로 지원자들의 SAT점수와 체력점수가 상당히 높고, 지원자들 사이에 별 차이가 없기 때문에 주로 리더십에서 입학 여부가 갈린다고 한다. 머리, 체력, 리더십 등 전반적으로 뛰어난 학생들이 선발되지만, 매련 5% 정도가 첫 여름을 넘기지 못하고 탈락한다. 첫 여름에 생도들이 받는 교육프로그램은 짐승병영(Beast Barracks)이라고 하는 6주간의 군사훈련이다. 짐승병영 프로그램을 통해 생도들은 체력, 정서 및 정신적 한계에 도전하게 된다. 흥미로운 사실은 우수한 생도들도 종종 짐승병영 프로그램을 견뎌내지 못하고 탈락한다는 점이다. SAT점수, 리더십 역량, 체력점수 등 그 어느 것도 생도들의 탈락과 성공을 설명하지 못했다. 미국 육군은 그 답을 찾기 위해 오랫동안 노력했지만 최근에야 오랜 지혜에서 그 단서를 확보했다.
 
## 만들어진 천재
"천재는 1%의 영감과 99%의 땀으로 이뤄진다(Genius is 1 percent inspiration and 99 percent perspiration)." 발명가 에디슨의 너무나도 잘 알려진 명언이다. 이는 에디슨 스스로 체험을 통해 습득한 지혜이기도 하다. 에디슨이 전구를 발명하기 위해서는 1천번 이상의 시행착오를 거듭해야 했다.  뉴튼이 사과가 떨어지는 것을 보고 중력의 법칙을 찾아 냈다는 일화 역시 99%의 노력이 1%의 영감과 결합한 사례다. 뉴튼은 수년간 중력과 적분의 문제를 풀기 위해 부단하게 노력했다. 풀리지 않는 문제를 고민하고 또 고민하기를 수년 간 반복하다, 어느 순간 사과가 떨어지는 것을 보고 ‘중력’이란 영감이 떠오른 것이다. 역사 속의 천재들이 무엇인가를 성취하면서 흘린 땀은 잘 알려져 있다. 노력이 성공의 핵심요인이라는 지혜는 오랫 동안 내려져 왔지만, 그 “땀”의 구체적 의미에 대해서는 정확하기 알지 못하고 있었다. "열심히 노력하는 것의 미덕”을 이해하기 위해서는 현대 과학이 필요했다.
마음의 작용을 과학적으로 탐구하는 학문인 심리학의 오랜 과제가 사람들이 갖고 있는 능력의 종류에 대한 탐구와, 능력을 발휘할 수 있는 다양한 방법에 대한 연구다. 일반적으로 많이 알려진 능력이 지적 능력이다.  지능이 높으면 대체로 사회적 성공으로도 이어진다. 시험성적이 좋아, 세칭 일류대학에 들어가,  졸업 후 좋은 일자리 잡고, 부와 명예를 쌓을 확률이 꽤 높은 편이다 (Sackett, Boreman, & Connelly, 2008). 그런데, 크게 성공하기 위해서는 지능과 같은 능력만으로는 부족하다는 것은 널리 통용되는 지혜다. 천재적 업적을 남긴 찰스 다윈은 스스로의 지적 능력이 남들보다 탁월하다고 여기지 않았다. 다윈은 그의 사촌인 프란시스 갈튼의 저서 <유전되는 천재성(Hereditary Genius)>읽고 보낸 서한에서 “나는 늘 사람들의 지적능력은 바보를 제외하고는 별 차이가 없다고 주장했네. 오직 열정과 지독한 노력만 다를 뿐이지”라고 했다. 미국 펜실베이니아 대학의 심리학자 안젤라 덕워스는 다윈이 꼽은 장기목 목표에 대한 열정과 지독한 노력에 주목했다. 덕워스는 이 두가지 요소 - 끈기와 열정 – 을 하나의 용어, ‘기개(Grit)’로 개념화했다 (Duckworth et al. 2007). 덕워스가 영화 <진정한 기개 (True Grit)>에서 영감을 얻은 용어다. 영화 <진정한 기개 (True Grit)>는 존 웨인 주연의 서부영화다. 어린 소녀가 부당하게 실해 당한 아버지의 원한을 갚는 과정을 그린 영화다. 누가 봐도 불가능한 목표를 아주 오랜 기간 추구해, 결국은 이뤄낸다는 이야기다. 기개는 실패, 역경, 슬럼프 등에도 불구하고 여러 해에 걸쳐 꾸준하게 목표를 향해 정진하는 것을 말한다. 성취하는 것을 마라톤으로 본 것이다. 몸과 마음에 한계에 달한 것 같은 고통이 밀려와도, 같은 것을 반복하고 또 반복해 지루하고 따분하더라도 목표를 바꾸지 않는 것이다. 영어 단어 grit은 일반적으로 음식물이나 물 등에 섞인 모래알이나 작은 돌을 의미한다. 눈에 들어가 껍껍한 느낌이 들도록 하는 모래같은 이물질을 가르킨다. ‘기계에 그릿을 넣다 (put grit in the machine)’이란 표현은 ‘일의 원활한 진행을 방해한다,’ ‘찬물을 끼얹다’ 등의 부정적 의미로 쓰인다. 이런 의미의 단어인 grit을 미국인들은 구어로 ‘기개, 기골, 불굴의 정신’ 등으로 쓴다. 그릿은 모래알 같은 것이 눈에 들어와도, 기계에 모래가 끼어 일이 원활하게 진행되지 않는 등, 뭔가 중간 중간 장애가 있더라도 개의치 않고 한가지 목표를 향애 꾸준하게 정진한다는 역설적 표현이다. 덕워스는 성공한 배우들의 향연인 아카데미상 수상자들의 데뷔작을 보라고 권유한다. 세계적 주목을 받는 명배우건만, 그들의 연기가 그다지 뛰어나지만은 않다. 그런 그들이 발군의 연기력을 발휘할 수 있었던 것은 지독한 노력의 결과다. 
기개는 자기통제력과 비슷하지만, 장기적 목표를 일관되게 추구한다는 점에서 다르다. 예를 들어, 자기통제력은 높지만, 기개의 수준이 낮은 사람의 경우, 일상생활에서 눈앞의 유혹은 뿌리칠 있다. 따라서, 시험성적도 좋고, 일상적으로 처리해야 하는 업무도 잘 해낸다. 그러나, 장기적 목표를 일관되게 추구하지 않기 때문에 하던 일을 바꾼다. 유능하기는 한데, 1,2년에 한번씩 직장을 옮기는 게 좋은 사례다. 기개는 성취욕과 다른 점이 있다. 성취욕이 높고 기개수준이 낮으면 너무 어렵지 않은 목표를 설정하는 경향이 생긴다. 너무 어려우면 성취할 수 없기 때문이다. 이런 기개의 특성은 왜 우수한 학생들이 웨스트 포인트의 짐승병영 프로그램을 버텨내지 못하는지 잘 설명해 준다. 능력은 있지만 인래력이 부족하다거나, 인내력은 있어도 장기적 목표에 대한 열정이 부족하면, 극한의 고통을 이겨내려 하지 않기 때문이다. 
덕워스는 과연 기개가 성공의 지표가 될 수 있는지 실증적 자료를 모았다. 덕워스가 찾은 곳은 웨스트 포인트. 고르고 골라낸 엘리트틀이 매년 5%씩 탈락해, 미국 육군이 그 원인을 찾기 위해 고심하던 곳이다. 덕워스와 미 육군 사관학교 당국은 2004년에 새로 입학한 생도 1200여명을 대상으로 기개, 여름훈련 통과여부, 자기통제력,  WCS, 학업성적 및 군사역량척도 (MPS: Military Performance Score)를 측정했다. MPS는 사관생도의 군인으로서의 잠재력을 종합적으로 평가하는 도구다. 책임감에서 높은 점수를 받아야 좋은 평가를 받도록 설계됐다. 연구 결과는 예측대로 기개가 다른 어떤 요인보다 생도들의 탈락 여부를 잘 예측했다. 기개 수준이 평균 점수보다 높은 생도들이 여름 군사훈련 프로그램을 마칠 확률은 60%가 넘었다. 기개와 비슷한 개념인 자기 통제력이 높은 생도들이 여름훈련을 마칠 확률은 50% 정도였다. 지능,체력, 리더십의 종합척도인 WCS는 여름 훈련 성공 여부와 관련이 없었다. 오히려, 미국 육군 당국이 우수한 생도의 선발 기준으로 활용하는 WCS 상위 25%에 들면 여름훈련에 탈락하는 경향이 높았다. 
기개는 지적 능력 향상과도 중요한 관계가 있다. 타고난 지능은 조금 떨어져도, 꾸준한 노력으로 보상할 수 있기 때문이다. 덕워스 연구팀은 미국 최고 명문대학인 펜실베이나 대학교  학부생들을 상대로 기개와 입학시험성적(SAT), 학업성적의 관계도 분석했다. SAT 점수가 낮아도, 기개가 높은 학생은 학업성적이 좋았다. 지적 능력이 다소 떨어져도 꾸준한 노력으로 좋은 성적을 유지할 수 있었던 것이다. 언어 천재의 지적 능력 경연인 2005년 스크립스 스펠링 비 결승전 참가자들에서도 비슷한 결과가 나왔다. 스크립스 스펠링 비는 미국 뿐 아니라 유럽 캐나다 뉴질랜드 등 세계 각지에서 언어에 비범한 능력을 지닌 어린이들이 맞춤법 지식을 겨루는 대회다. 덕워스 연구팀은 결승전 참가자들의 기개, 자기 통제력, 언어지능지수(IQ), 공부시간을 측정한 뒤, 최종전 참여 여부 등과의 관련성을 분석했다. 2005년 대회에서는 총 19회전에 걸쳐 실력을 겨뤘다. 결승전에 참가했던 학생들은 지능이 높은 학생이 아니라, 기개가 높은 학생들이었다. 지능이 높은 학생들은 10-15회전까지는 진출했지만, 최종 결승전에 도달하지는 못했다. 묘하게도 지능과 기개는 역관계였다. 지능이 높은 학생들은 기개의 수준이 떨어지는 경향이 있었던 것이다. 즉, 지능이 높은데도 불구하고 결승전에 도달하지 못한 것은 노력의 결핍이었다고 할 수 있다. 덕워스는 결승전에 도달한 학생들의 어떻게 맞춤법 대회를 대비해 연습했는지 분석했다. 특이할 점은, 기개 수준이 높은 학생들의 공부방식이었다. 이들은 단지 공부하는데 오랜 시간만 투자한게 아니었다. 의도적으로 어렵고 풀기 힘든 문제를 추려내 이 부분을 집중적으로 공략했다. 스스로에 어려운 과제를 주고, 극복하기를 반복했기에 천재적 재능을 갖게 된 것이다.

## 1만시간의 비밀
기개에 대한 연구를 통해 말콤 글래드웰의 <아웃라이어: 성공의 비밀을 발견한 사람들 (Outliers: Why some people succeed and some don’t)>로 널리 알려진 1만시간의 법칙에 숨어있는 비밀을 알 수 있다. 글래드웰은 성공하는 사람들의 비밀로 1만시간 동안의 의도적인 훈련을 들었다. 특출난 사람들과 그렇지 않은 사람들의 차이는 연습량의 차이에 있었다는 것이다. 글래드웰은 인터넷의 에디슨이라 불리는 빌 조이의 예를 들어 연습량의 중요성을 강조했다. 빌 조이가 컴퓨터의 역사를 새로 쓸 수 있었던 역량을 쌓을 수 있었던 것은 그가 어린 시절 부터 컴퓨터 프로그래밍에 몰입할 수 있었기 때문이다. 모짜르트같은 음악의 신동도 예외가 될 수 없다. 성인이 되기 이전에 1만시간 이상의 연습량을 채워야, 타고난 재능이 빛을 발하게 한다는 것. 글래드웰이 성공과 1만시간의 연습량에 대한 영감을 얻은 곳은 심리학자 앤더스 에릭슨의 전문가에 대한 연구에서다. 에릭슨은 그의 동료와 함께 베를린의 세계적인 음악가 양성기관인 서베를린 음악원(Hochscule der Kuenste)의 바이올린 전공 학생들의 연습량을 분석했다 (Ericsson, Krampe, & Tesch-Romer, 1993). 에릭슨은 음악원 교수진의 도움을 받아 학생들을 세 집단으로 구분했다. 세계적 연주가로 성장할 최우수 학생, 직업적 연주가로 활동할 수준의 우수 학생, 그리고, 음악 교사가 될 만한 실력의 평범한 학생들로 구분했다. 세 집단의 학생들에서 두드리지게 나타난 것은 음악에 대한 재능이 아니었다. 연습량과 낮잠이었다. 최우수 학생집단은 20세가 되기까지 1만시간의 연습량을 채웠다. 반면, 우수 집단의 학생집단은 7천시간 정도. 평범한 학생집단의 연습시간은 4천시간 정도 였다 (주: 흥미로운 사실은 최우수 집단의 학생은 오후 2시 정도에 낮잠을 30-40분 정도 즐겼다는 점이다. 반면, 평범한 학생들은 주중에 낮잠을 전혀 자지 않았다.) 에릭슨과 그의 동료들은 이 연구를 근거로 10년간의 부단한 연습이야말로 전문가의 역량을 쌓을 수 있는 핵심 요건이라는 근거로 내세웠다. 
글래드웰은 1만시간 연습의 비결을 사회환경에서 찾았다. 빌 조이가 컴퓨터의 새 역사를 쓸 수 있었던 것은 그가 10대 시절 미시간 대학의 컴퓨터센터에 접근할 수 있었기 때문이란 것이다. 마이크로 소프트를 세운 빌 게이츠, 빌 게이츠와 함께 개인용 컴퓨터 혁명을 이끈 폴 알렌과 스티브 발머, 애플 신화를 창조한 스티브 잡스, 구글의 에릭 슈미트 등도 비슷한 사례다. 이들의 공통점은 1950년대에 태어나 어느 누구보다 정보통신 혁명의 물결을 먼저 접할 수 있는 환경에 노출됐다. 즉, 천재는 개인의 타고난 능력 뿐 아니라, 타고난 능력이 재능으로 환원되도록 할 수있는 사회환경이 필요하다는 것이다. 글래드웰은 이를 ‘Capitalize’란 표현으로 설명한다. ‘자본을 투여하다’는 의미의 영어 단어인 ‘캐피털라이즈’ 에는 이용한다는 의미가 있다. 무엇인가를 이용해 자본이 되도록 한다는 것이다. 사람에게 투자해 그 사람의 역량이 사회의 자본이 되게 한다는 의미다. 글래드웰은 캐피탈라이즈를 가로 막는 요인으로 가난, 아둔, 문화 등 세가지를 꼽았다. 빈곤이 캐피탈라이즈를 가로막는 이유는 명확하다. 가난하면 10년 안에 1만시간 연습에 투자할 여력이 없다. 10년 안에 1만시간이란 연습량을 채우려면, 전적으로 연습에만 매달려야 가능하다. 먹고 사는 문제를 해결하고 남는 시간을 통해 채울 수 있는 양의 시간이 아니다. 가난하면 미래를 위한 투자에 전념할 수 없다. 아둔함은 사회적 시스템을 말한다. 캐나다 하키 선수 선발 시스템이 그 예다. 캐나다는 하키에 열광하는 나라다. 그만큼 하키에 들이는 공이 크다. 그런데, 유명한 하키 선수들을 보면 대부분 1-3월 생이다. 8-9월 생이 간혹 있지만, 12월 생은 없다. 그 이유는 간단하다. 하키 선수는 10세 이전에 선발하는데, 1월에 선발이 이뤄진다. 8-9세의 1월 생과 12월생의 발육차이는 크다. 즉, 능력있는 아이를 뽑는게 아니라, 단지 11개월 일찍 태어나 발육상태가 좋은 아이를 선발해 집중적으로 투자한다는 것이다. 선수선발을 8-9월에 한번 더 한다면, 우수한 선수를 선발할 가능성이 두배는 올라간다는 이야기. 문화적 요인도 크다. 미국에서 한국인 등 아시아 국가들의 이민자들 중에 성공한 사람들이 많다. 이민 1세대가 가난했음에도 말이다. 아시아 국가들의 문화가 열심히 노력하는 것을 장려하는 문화가 있기 때문이다. 지능이 110정도인 아시아계 사람이 성취하는 사회적 보상이 지능 120정도되는 유럽계 사람들의 사회적 보상과 비슷하다고 한다. 
아웃라이어에서 강조한 의도적인 1만시간과 성공의 관계는 많은 사람들의 공감을 샀다. 그러나, 1만시간을 연습할 수 있는 요인이 주워진 환경이라는 글래드웰의 주장에는 비판이 있다. 뉴욕타임즈 컬럼니스트인 데이빗 브룩스는 ‘군중 속에서 잃다 (Lost in the Crowd)’라는 칼럼을 통해 사회가 개인의 성공여부를 결정짓는다면 개인의 역할은 어디에 있냐며 글래드웰의 아웃라이어를 비판했다. 1만시간 연습은 개인의 부단한 의지와 노력의 결과라는 것이다. 글래드웰의 반박이 이어졌다. 글래드웰은 개인 블로그를 통해, 개인의 의지력 역시 개인에게 주워진 환경의 결과라고 했다. 글래드웰은 개인의 의지와 노력을 폄하한게 아니라고 반박하면서도, 개인의 불굴의 의지력을 갖게 되는 것은 개인이 선택한게 아니라는 것이다. 예를 들어, 법률가가 되기 위해서는 부단한 노력이 필요하다. 그런데, 미국사회에서 성공한 법률가를 보면 유태인들이 상당히 많다. 이는 유태인들에게 노력하는 유전자가 있기 때문이라기 보다는 유태인 이민사회가 노력하는 문화를 갖고 있기 때문이란 것이다. 브룩스의 비판을 실용성이 없다고도 반박했다. 사회적 문제를 해결하는데 개인의 의지력을 향상시키는데 들이는 노력보다는 가능한 모든 어린이들에게 1만시간 연습량을 채울 수 있는 사회환경을 조정하는 것이 더 수월하고 실용적이라고 주장했다. 브룩스가 글래드웰의 반론을 다시 한번 반박했다. ‘천재: 현대적 관점 (Genius: the Modern view)’이란 제목의 컬럼이다. 천재가 되기 위해서는 무엇보다 1만시간의 연습을 감내할 개인의 의지력이 우선이라는 것이다. 천재가 천재가 된 것은 이들에게 어떤 신비한 능력이 있는게 아니라, 이들이 힘겹고 지겨운 연습을 수행해 낼 수 있는 능력이 있기에 가능했다는 주장이다.              
글래드웰과 브룩스가 서로 논박했지만, 실은 서로 다른 이야기를 하고 있다. 둘다 틀린 이야기를 한게 아니다. 글래드웰의 주장대로 개인의 능력이 있어도 여건이 안되면, 그 능력은 사장되고 말 가능성이 높다. 중국과 인도의 시골에서 혹은 아프리카에서 근근이 생계를 이어가는 수십억명의 사람들 중, 환경만 제대로 갖춰졌으면 천재적 능력을 발휘할 사람이 적지 않다. 그렇다고 브룩스의 주장이 틀린 것도 아니다. 개인의 능력, 특히 꾸준히 노력하는 능력이 천재성과 긴밀하게 관련돼 있다는데는 이의가 없다. 아무리 여건이 마련된다 해도 1만시간 연습을 채우는 사람은 소수에 불과하다. 비록 언론인들 사이의 논쟁이긴 하지만, 브룩스와 글래드웰의 논쟁에는 학계의 오랜 숙제가 담겨 있다. 꾸준히 노력하는 능력을 후천적으로 양육하는 것이 가능한가에 대한 것이다. 기개 (장기적 목표에 열정과 역경을 이겨내는 인내력)와 자기 통제력은 선천적으로 타고난 것인가, 아니면 후천적으로도 양육할 수 있는 것일까?

## 마음의 근육
사람은 여느 동물들과 구별되는 특별한 점이 많다. 그 중 하나가 뇌의 성숙기간이다. 인간의 뇌가 충분히 성숙해지기까지 무려 25년 정도 걸린다. 어지간한 동물의 한 생애를 이루는 기간이다. 성장 단계별로 발달하는 두뇌의 기능도 다르다. 어린이와 청소년 및 성인이 달리 생각하고, 달리 행동하는 이유도 뇌의 발달정도가 다르기 때문이다. 시각을 처리하는 후두엽이 우선적으로 발달하고, 운동과 지각을 처리하는 전두엽과 두정엽이 발달한 다음, 최종적으로 10대와 20대초에 사회활동을 처리하는 전전두엽이 집중적으로 발달한다 (Lenroot Giedd, 2006 brain development in children and adolescents). (그림: http://www.loni.ucla.edu/~thompson/DEVEL/dynamic.html). 성인이 됐다고 두뇌가 고정되는게 아니다. 두뇌는 사용하면 사용하는 만큼 발달한다. 비유하자면, 사람의 마음은 일종의 근육이다. 근육을 단련하면 크고 단련할 수록 강해지는 것처럼, 머리도 쓰면 쓸수록 좋아진다. 
지능은 크게 두가지로 구분할 수 있다. 고정지능(Crystallized Intelligence)과 유동지능(Fluid Intelligence)이다. 고정지능은 축적된 지식을 반영한다.  유동지능은 문제를 해결하는 능력이다. 이론을 사례에 적용한다거나, 사례에서 이론을 추출할 때 필요하다. 유동지능은 뇌의 실행기능(executive function)을 통해 작동한다. 실행기능에는 단기 기억 (Short-term Memory), 주의조절 (Attentional Control), 및 제어조절 (Inhibitory Control)이 있다. 문제를 풀려면, 문제해결에 필요한 정보를 머리 속에 올려놓고 있어야 하고 (Short-term Memory), 특정 문제에 주의를 집중하고, 필요에 따라 주의집중 대상을 바꾸거나 유지하고 (Attentional Control), 문제해결에 불필요한 요인에 꾀지 않도록 제어할수 있어야 한다 (Inhibitory Control). 유동지능은 지식을 많이 쌓는다고 생기는 게 아니기 때문에, 이제까지 후천적으로 향상할 수 있는 능력이 아니라고 믿고 있었다. 유전적으로 타고난 능력으로 여겼다. 이런 이유로 학교교육에서는 유동지능 향상을 상대적으로 소홀히 하는 경향이 있다. 학교교육은 대체로 고정지능 향상에 중점을 둬 지식 전달위주의 교육이 이뤄진다. 
교육에 의해 향상되는 것은 고정지능만 아니다. 유동지능도 훈련에 의해 향상시킬수 있다. 미국 미시건 대학 심리학과 수전 재기와 그의 동료들은 독일 대학생 70명에게 작업기억에 부하를 주는 이중 엔백 (Dual N-back) 훈련을 하도록 했다. (주 혹은 별도 박스: 엔백은 작업기억에 부하를 주기 위해 고안된 프로그램이다. 왜 N-back인가 하면, 훈련강도가 세질수록 작업기억에 올려야 하는 정보의 양이 N만큼 증가하기 때문이다. 즉, 1-back훈련에서는 한단계 전의 정보를 기억해야 하고, 2-back훈련에서는 두단계 전의 정보까지 기억해야 한다. 이렇게 3-back, 4-back, 계속 올라간다. 보통 2-back만 돼도 수행하기 상당히 힘들다.  예를 들어, "가 타 피 타"라는 소리가 나올 때 "피"라는 소리가 들리는 시점에서 "가"는 2-back, "타"는 1-back이 된다. 만일 2-back 작업이라면, 2글자 전의 글자와 일치하는지 여부를 맞추는 것이고, 1-back작업이면, 1글자 전의 글자와의 일치여부를 맞추는 작업이다. 일치하면 컴퓨터 키보드의 화살표 키를 누르고, 일치하지 않으면 아무 키도 누르지 않는다. 예를 들어, 2-back작업이라고 할 때, "가 타 피" 등의 순서로 들린다고 하자. 이때 “피”라는 소리가 들리는 시점에서 2-back의 글자가 무엇이었는지 기억해야 한다. 2-back에 들었던 글자가 “가”였으므로 “피”와 일치하지 않는다. 따라서 아무 키도 누르면 안된다. 네번째에 들린 글자가 “타”라고 하자. 2-back에 들렸던 글자가 “타”로 일치하므로, 이때는 지정된 자판의 키를 눌러야 한다. 엔백 작업을 잘 하려면 단기적으로 어떤 글자를 들었는지 기억해야 할 뿐 아니라 (단기기억), 어떤 글자를 들었는지 주의를 세밀하게 기울여야 한다. (주의조절) 게다가, 2회 이전의 글자만을 기억해야 하기 때문에, 그 이전의 글자는 기억에서 제거해야 한다 (제어조절). 작업기억에는 언어기억과 공간기억 두가지 요소가 있다. 따라서 엔백훈련의 작업기억에는 두가지 요소가 함께 들어 있다. 1-back의 경우, 가, 타, 피, 등의 소리를 순차적으로 들려주면서 한단계 직전의 소리가 반복되면 왼쪽 화살표 키를 눌러야 한다 (언어기억). 동시에 사각형의 움직임 (공간기억)을 보여주면서, 한단계 직전의 위치가 반복되면 오른쪽 화살표 키를 눌러야 한다. 즉, 언어정보와 공간정보를 동시에 처리해야 한다.) 실험 참가자들은 네 집단으로 나뉘어 각각 8일, 12일, 17일, 19일간 엔백 훈련을 하루 25분씩 받았다. 참가자들은 훈련기간이 경과할 수록 엔백 훈련의 강도를 높여갈 수 있었다. 첫날은 대체로 2-back이었지만, 일주일 후에는 4-back까지 훈련 강도를 높일 수 있었다. 19일간 훈련을 받을 참가자들은 최고 6-back 작업까지 수행해 냈다. 훈련 전과 후에 각각 RAPM (Raven’s Advanced Progressive Matrices) 테스트 혹은 보다 어려운 BOMAT (Bochumer Matrizen Test) 등과 같은 지능검사를 실시했다. 결과는 예측대로 훈련기간이 길 수록 지능향상이 두드러졌다. 8일간 훈련을 받은 참가자들은 지능이 약 0.5 포인트 증가했지만, 19일간 훈련 받은 사람들은 약 4.5 포인트 증가했다. 불과 19일간 25분씩 훈련했는데, 지능지수가 4,5포인트나 증가한 것이다.

더욱 흥미로운 점은 지능향상이 단지 작업기억에 부하를 주는 훈련을 통해서만 이뤄지는게 아니란 사실이다. 미국 오리건 대학 심리학과 이위안 탕과 마이클 포스너 연구팀은 미시건 대학의 수전 재기의 연구팀과는 반대의 접근을 시도했다 (Tang et al., 2007). 실험 참가자들에게 명상훈련을 시켰다. 작업기억에 고강도 부하를 주는 대신, 마음을 평안한 상태로 다스리도록 한 것이다. 탕과 포스너 연구팀은 마음챙김 훈련을 하루 20분씩 5일간 실시했다. 참가자들은 훈련 참여 전과 후에 각각 RSPM (Raven’s Simple Progressive Matrices) 테스트로 지능 검사를 실시했다. 예측대로, 명상훈련 후에 지능이 향상됐다. 미국 웨이크 포리스트 대학의 신경생물학과의 파델 제이단 연구팀도 비슷한 연구결과를 얻었다. 명상경험이 없는 미국 대학생들을 상대로 하루 20분씩 5일간 명상훈련을 실시한 후, 엔백작업 등의 테스트를 통해 명상참가자들의 인지능력 향상을 확인했다 (Zeidan, 2010). 지능이 높다는 것은 기억용량이 큰 것만을 의미하지 않는다. 뇌의 자원을 효과적으로 활용하는 것을 말한다. 사람의 뇌는 무한한 자원이 아니다. 특히, 주의력처럼 실행기능과 관련된 뇌의 기능은 쉽게 고갈되는 ‘값 비싼 자원’이다. 그런데, 글을 쓰거나, 문제를 해결하는 등의 작업에는 뇌의 에너지를 많이 소모한다. 따라서, 머리가 좋다는 것은 실행기능을 작동하는데  들어가는 에너지를 효과적으로 활용하는 것을 의미한다. 실제로 주의력을 집중적으로 사용해야 하는 엔백 작업을 할 때, 지능이 높은 사람과 낮은 사람 사이의 두뇌 활용 효율성에서 크게 차아가 난다 (Jaeggie, 2007). 수전 재기 연구팀은 실험 참가자들에게 엔백 작업을 하도록 한뒤, 뇌영상장치 (fMRI)로 뇌의 활동성을 측정했다. 엔백작업을 정확하고 빠르게 수행한 사람들은 실행기능에 관여하는 뇌의 부위가 덜 활성화했다. 즉, 뇌의 자원을 효율적으로 사용하고 있었다는 것이다. 근육이 커 힘이 센 사람이 무거운 물건을 들어 올릴 때 그다지 힘을 쓰지 않아도 되는 것과 같은 이치다.

==(박스: 마음챙김명상은 말그대로 유념(Mindful)하는 명상이다. 아무 생각없이 넋놓고 (mindless) 있는게 아니라, 현재의 순간 순간에 유념해야 한다. 말 그래도 마음을 챙겨야 한다. 보통 긴장을 푼 상태에서 숨에 주의를 기울인다. 숨을 천천히 들이쉬고, 내쉬며 (복식호흠으로) 그 숨이 들어가고 나가는 지점 (단전, 혹은 코)에 주의를 기울인다. 훈련 초기에는 의식적으로 들숨과 날숨에 주의를 기울인다. 마음챙김 명상에서는 주의를 기울이는 그 자체보다, 명상 주에 주의가 흩어지는 순간을 어떻게 대응하냐가 중요하다. 주의가 흩어지면, 억지로 주의를 기울이려고 하거나, 자책하지 않는다. ‘주의를 놓쳤구나’하고 깨닿고 다시 들숨과 날숨에 주의를 기울인다. 몸과 마음의 상태를 챙겨야 하기에, 마음챙김 명상이다. 이런 과정을 반복하면서 명상 훈련이 쌓이면 숨에 의식적으로 주의를 기울이지 않아도 마음을 챙길 수 있게 된다. 명상훈련이 지능향상으로 이어질 수 있는 이유가 바로 주의를 기울이는 능력이 향상되기 때문이다. 실제로 뇌영상 연구에서, 명상 수행을 하는 중, 두뇌의 실행기능과 관련된 부위가 활성화하는 것으로 나타났다 (Short et al., 2007).
과학계에서 명상에 관심을 돌리게 된 것은 스트레스와의 관련성 때문이었다. 심장병 전문가인 하버드 의과대학의 허버트 벤슨은 스트레스가 심장에 나쁜 영향을 준다는 사실에 주목했다. 벤슨이 내놓은 처방은 마음을 다스리는 것이었다. 이완함으로써 스트레스에서 오는 나쁜 영향을 막고자 한 것이다. 실제로, 벤슨의 처방은 효과가 있었다. 벤슨의 처방은 서양 의학계에서 코페르니쿠스적인 전환에 해당하는 사건이다. 몸의 병을 마음을 다스려 해결하고자 했기 때문이다. 벤슨은 미국 최고의 병원 중 하나인 메사추세츠 종합병원에 ‘몸과 마음 의학을 위한 벤슨-헨리 연구소(Benson-Henry Institute for Mind Body Medicine)’를 설립, 그의 프로그램을 운영하고 있다. 몸의 치료에 명상을 적극적으로 도입한 이는 메사추세츠 대학교 의과대학의 존 카밧-진이다. 카밧-진도 심장병과 스트레스의 관계에 주목, 마음을 다스려 몸의 질환을 예방하고자 했다. 카밧-진은 그의 명상 프로그램을 MBSR(Mindfulness-Based Stress Reduction)로 체계화해 보급하고 있다. MBSR프로그램의 효과는 미국내 주요 의과대학을 중심으로 건강에 대한 효과를 중심으로 연구가 이뤄지고 있다. 한국에는 마인드플러스 스트레스 대처 연구소 장현갑 소장이 카밧-진의 MBSR프로그램을 소개했다.)== 

## 마음의 기술
힘만 세다고 무거운 역기를 들어올릴 수 있는게 아니다. 균형과 타이밍을 정교하게 조절할 수 있는 기술이 필요하다. 마음의 근육도 마찬가지다. 힘을 제대로 발휘하려면 기술이 있어야 한다. 그 기술 중 하나가 틀짓기(Framing)다. 같은 상황이라도 어떤 틀로 접근하냐에 따라 생각과 행동이 달라진다. 재능을 타고난 것이 아닌 ‘마음의 근육’이란 틀로 접근하는 것이 좋은 예다 (Magen & Gross, 2007). 근육은 쓰면 쓸수록 향상된다는 것이 눈에 명확하게 들어오기 때문이다. 스탠포드 대학 심리학과의 이란 마젠과 제임스 그로스는 실제로 ‘마음의 근육’이라고 틀을 짓는 기법이 유혹을 이겨내는데 어느정도 효과적인지 실험해 보았다. 실험에 참가한 학생들은 두 집단으로 나뉘어, 컴퓨터 스크린에 나타난 수학문제를 풀도록 했다. 동시에 컴퓨터 스크린 옆의 TV모니터에는 인기 코미디 프로그램을 틀어 놓았다. 실험 참가자들에게는 테스트의 목적이 참가자들의 수학능력을 테스트하기 위함이라며, 90점 이상을 받을 경우, 10달러를 상금으로 받는다고 했다. 5분간 문제를 풀도록 하면서, TV를 어느 정도 보는지 비디오로 기록했다. 실험 참가자들을 두 집단으로 나눴다. 한 집단은 문제 풀기에 앞서, 첫 과제와 똑같이 테스트의 목적이 참가자들의 수학능력을 테스트하기 위함이라며, 90점 이상을 받을 경우, 10달러를 상금으로 받는다고 했다. 다른 집단에는 코미디 프로그램을 보지 않고 문제풀이에 집중하라며, TV에서 방영되는 프로그램으로 실험 참가자들의 의지력을 테스트한다고 했다. 결론은 10달러의 보상을 제시받은 집단은 TV를 많이 본 반면, 의지력을 테스트한다고 한 집단은 TV를 덜 봤다. 코미디 시청이란 유혹을 이겨내는 것을 의지력, 즉 마음의근육이라는 틀로 접근하는 것이 효과적이라는 근거가 되는 연구다.
실제 교육현장에 적용한 연구도 있다 (Blackwell, Trzesniewski, & Dweck, 2007). 스탠포드 대학교 심리학과 캐롤 드웩 연구팀은 미국 뉴욕의 한 중학교 1학년 학생 373명의 지능에 대한 마음가짐(mindset)과 1년 후의 학교 성적을 분석했다. 드웩 연구팀은 두가지 마음가짐을 추려냈다. 하나는 성장형 마음가짐이고, 다른 하나는 고정형 마음가짐이다. 성장형 마음가짐은 지능이란 것이 유연한 것이라 개발될 수 있다고 믿는 마음가짐이다. 고정형 마음가짐은 지능을 고정된 능력이라고 보는 마음가짐이다. 중학교 1학년때 고정형 마음가짐이나 성장형 마음가침을 갖고 있는 학생들의 수학점수는 큰 차이가 없었다. 고정형 마음가짐을 갖고 있는 학생 평균은 71점인 반면, 성장형 마음가짐인 학생은 평균 73점이었다. 그런데, 1년 후의 점수는 크게 달랐다. 성장형 마음가짐을 갖고 있는 학생들은 성적이 꾸준하게 올라, 평균 76점이 됐다. 반면, 고정형 마음가짐을 갖고 있는 학생들은 성적이 오르지 않았다. 오히려 조금 떨어졌다.  성장형 마음가짐이 학생들로 하여금 노력하도록 하기 때문이었다. 
성장형 마음가짐이 학생들의 성취에 중요한 역할을 하고 있다는 사실을 확인한 드웩 연구팀은 학생들에게 성장형 마음가짐을 마음의 기술로 가르쳐 보기로 했다. 뉴욕의 한 중학교의 1학년 99명을 대상으로 일주일에 한번씩 25분간 8회에 걸쳐 성장형 마음가짐에 대해 교육했다. 1주와 2주차에는 두뇌 과학에 대해 교육했다. 뇌의 구조와 기능, 신경세포의 구조, 신경전달 물질 등에 대한 내용이다 (주: 드웩의 두뇌 교육프로그램은 www.brainology.org에 소개돼 있다.) 3주와 4주차에는 “나는 나의 지능을 향상시킬 수 있다”라고 큰 소리로 읽게 했다. 신경세포의 망에 대한 그림을 이용해 학습을 통해 사람들의 두뇌가 어떻게 똑똑해 지는지 알도록 했다. 교육 효과를 비교하기 위해 대조집단을 운영했다. 대조집단에서는 기억력에 대한 교육을 했다. “기억”이라고 큰 소리로 읽게 한 다음, 여러 가지 사물을 잘 기억할 수 있는 기법에 대해 교육했다.  5주와 6주차에는 고정관념을 탈피하는 교육했고, 7주와 8주에는 학습이 어떻게 사람을 똑똑하게 할 수 있는지에 대해 학생들이 토론하게 했다. 대조집단에서는 기억력과 두뇌에 대해 토론하도록 했다. 성장형 마음가짐 교육효과는 극적으로 나타났다. 성적이 떨어지던 학생들이 교육 후에 성적이 크게 올랐다. 숙제와는 담을 쌓고 지내고, 늘 낙제점을 면하지 못하던 학생의 태도가 변해 열심히 공부하기 시작했다. 물론 성적도 크게 올랐다. 반면, 기억력 기술을 교육받은 학생들의 태도나 성적에는 별다른 변화가 없었다. 드웩은 성장형 마음가짐을 교육할 때 한 학생의 반응을 잊을 수 없다고 했다. 반항아 기질이 풍기던 그 학생은 드웩을 빤히 쳐다보면서 “그럼, 내가 멍청할 필요가 없단 말이죠?”라고 했다고 한다. 

학생들이 성장형 마음가짐을 갖게 되는데는 부모와 교사의 역할이 중요하다. 드웩은 아이들에게 칭찬할 때는 열심히 노력한 것에 가치를 둬야지 머리가 좋다는데 가치를 두면 안된다고 강조한다 (Dweck, 2007). 능력을 칭찬할 경우, 학교에서 배우는 것에 흥미를 잃고 노력을 게을리 하게 된다는 것. 드웩은 초등학교 시절 두각을 나타냈던 조나단이란 아이를 예로 들었다. 조나단은 모든 과제물을 척척 해냈다. 다른 급우들이 쩔쩔 매는 문제도 쉽게 풀어냈다. 조나단의 부모는 조나단에게 특별한 재능이 있다고 칭찬했다. 그런데, 조나단이 중학교 1학년이 됐을 때, 학교 공부에 흥미를 잃고, 숙제도 하지 않고, 시험공부도 하지 않았다. 성적이 크게 떨어졌다. 조나단은 학교에서 하는 공부가 따분하다고 불평했다. 드웩은 실험을 통해 노력에 칭찬의 효과를 확인했다 (Mueller & Dweck, 1998). 뉴욕의 초등학교 학생들에게 지능검사를 실시하면서 한 집단에는 “너 정말 똑똑하구나”라고 칭찬했다. 다른 집단에는 “너 정말 열심히 했구나”라고 했다. 지능검사를 다시 실시했을 때 노력에 대해 칭찬받은 학생들은 성적이 30%나 향상됐다. 반면, 능력에 대해 칭찬받은 학생들은 반대로 20%나 떨어졌다. 같은 연구에서 능력에 대해 칭찬받으면 성적이 떨어지는 이유를 제시했다. 지능에 대해 칭찬받은 아이들은 아이들은 뭔가 잘하고 있다는 것을 보여주기 위해 어려운 과제를 피하고, 쉬운 것만 선택하게 된다는 것이다. 따라서 조금 어려운 상황에 부딪히면 극복하려고 노력하기 보다, 슬쩍 피해버리고 만다. 게다가, 과정을 즐기지도 못한다. 문제풀이를 하면서 과제가 어느정도 즐거웠는지에 대한 응답에서 노력에 대한 칭찬을 받은 아이들은 전반적으로 문제풀이가 즐거웠다고 답했다. 성장형 마음가짐을 갖고 있는 경우, 문제해결 자체가 보상이 되기 때문이다. 아이들이 노력에서 즐거움을 찾게 되는 지혜를 얻은 것이라 할 수 있다. 

## 한국의 교육
한국사회에 대한 불만을 하나 꼽으라면, 교육문제가 빠지지 않는다. 잠자리에 들어 있어야 할 새벽 1시에는 학원에서 공부하고, 정작 공부하고 있어야 할 낮 1시에는 학교에서 부족한 잠을 보충하고 있는 것이 한국교육의 현실이니 말이다. 누구나 부조리하다고 느끼면서도 어쩔 수 없이 끌려가야만 하는 현실을 받아들이는 사람도 있고, 거부하는 사람도 있다. 자녀 교육을 위해 아예 고국을 등지거나, 가족간 생이별을 선택하기도 한다. 한국의 교육문화에 대한 거부감은 단지 학생들에게 과도한 공부부담을 지우기 때문만은 아니다. 오히려 ‘젊어 고생은 사서도 한다’는 말이 있듯, 고생 자체가 문제가 아니다. 문제는, 고생하고 경쟁하는 내용이 그다지 합리적이지 않다는 데 있다. 인생이 대학입시로 끝나는 것이 아님에도 대학입시 자체에 모든 것을 거는 경향이 있다. 즉, 장기적인 목표를 설정하고 목표를 성취하는데 필요한 능력을 하나 하나 쌓아가도록 하기 보다, 당장 눈앞의 시험점수 올리기 경쟁에만 집중한다. 이런 예는 시험성적 향상에 직접적인 관련이 없어 보이는 과목에 대한 홀대에서 드러난다. 예를 들어 체육 같은 과목은 수험비중이 큰 수학이나 영어 점수 향상에 도움이 되지 못하는 것처럼 보인다. 오히려 공부할 시간을 빼앗는 것으로 여긴다. 실제로 일선 학교에서 주요 입시과목의 수업시간은 늘리고, 체육 같은 과목은 뒷전으로 밀리고 있다. 심지어 체육시간을 아예 없앤 학교도 있다 (경남일보, 오마이뉴스). 한국의 교육문화가 ‘교육’을 하기보다 시험점수 향상에만 집중하는 좋은 예다. 시험점수라고 하는 것은 교육이 제대로 되고 있는지를 측정하기 위한 지표에 불과한데, 이 지표 향상에만 집중하는 것은 주와 객을 바꾸어 놓은 것이다.

그렇다면, 과연 시험점수 향상에만 집중하는 근시안적인 교육문화는 정말로 학생들의 시험점수를 올리는 데 도움이 될까? 이에 대한 답은 우리의 두뇌를 이해하는 데서부터 시작해야 한다. 공부뿐 아니라 모든 사람의 생각과 행동은 뇌의 작용이기 때문이다. 사람의 두뇌는 몸의 일부다. 영양이 제대로 공급돼야 하고, 적당히 쉬고, 움직여 줘야 제 기능을 발휘할 수 있다. 응용학습심리학자이자 발달분자생물학자인 존 메디나 교수는 그의 두뇌과학에 대한 베스트셀러 <브레인룰즈>의 첫 장을 운동과 두뇌의 관계로 시작한다. 운동이 두뇌발달에 필수 불가결한 이유에 대해, 메디나 교수가 찾은 답은 간단하다. 인류는 움직이며 살아 왔다는 것이다. 문명사회를 이루기 전 인류가 하루에 움직이는 거리가 무려 10-20km나 되는 것으로 추정한다. 하루 10km이상을 움직이며 살아온 게 수백만년. 이렇게 몸을 움직이며 사는 동안 인류의 두뇌가 형성됐다. 이는 역으로 하루 10km이상 몸을 움직일 때 인류의 두뇌가 정상적인 기능을 수행할 수 있다고도 할 수 있다. 운동이 두뇌발달에 필수 불가결한 이유는 운동을 해야 뇌에 산소의 공급이 원활하게 이뤄지기 때문이다. 운동을 하면 두뇌를 포함한 온 몸으로의 혈액순환이 원활해 진다. 공부하는데 필요한 에너지 공급뿐 아니라, 뇌에 쌓이는 독성물질 제거도 원활해진다. 운동이 두뇌에 좋은 또 다른 이유는 BDNF(Brain Derived Neurotrophic Factor)라는 단백질 때문이다. BDNF는 신경세포들이 젊고 건강한 상태를 유지하도록 할 뿐 아니라, 새로운 신경세포의 형성을 촉진한다. 메디나 교수는 BDNF를 뇌에 뿌려주는 비료에 비유했다. 실제로, 운동시간을 줄이고 대신 공부시간을 늘인 경우에는 학업성적 향상으로 이어진다는 증거는 없는 반면, 운동이 학생들의 학업성적 향상된다는 연구는 꽤 많이 축적돼 있다 (Hillman, Erickson, & Kramer, 2008). 운동과 학업성적의 관계는 역설적인 측면이 있다. 공부시간 늘린다고 학업성적 향상으로 이어지지 않는 반면, 운동하기 위해 공부시간을 줄였는데도, 오히려 학업성적이 향상되기 때문이다. 이는 운동을 통해 학생들의 두뇌가 공부를 잘 할 수 있는 상태가 되기 때문이다. 운동을 해야 효과적으로 공부할 수 있는 능력이 형성된다는 것이다. 공부를 잘하려면 두뇌가 좋아야 하는데, 운동을 해야 두뇌가 좋아진다. 대학입시에 모든 것을 걸도록 하는 입시문화가 청소년들의 잠재적 역량을 심각하게 갉아 먹고 있는 셈이다. 운동시간 없애고, 쉬는 시간 줄이고, 잠자는 시간 아껴 공부하도록 하는 입시문화가 청소년들의 뇌를 망가뜨리고 있다 해도 과언이 아니다.

## 수면과 두뇌의 관계
잠은 단지 뇌가 쉬는 게 아니다. 자면서, 우리의 뇌는 학습한 내용을 통합하고 조직한다. 이미 배운 내용을 써먹는 사람들은 5시간 정도만 자도 뇌기능에 별 지장이 없다고 한다. 그런데, 새로운 내용을 지속적으로 익혀야 하는 학생들은 최소한 7시간 반은 자는 게 학습에 유리하다. 잠을 자면서 몸과 마음을 쉬는 것 뿐만이 아니라, 배운 내용을 정리하고 조직하기 때문이다. 잠은 다 똑 같은 게 아니고 여러 종류의 잠을 주기적으로 반복한다. 대표적인 잠의 종류가 깊은 잠과 REM(Rapid Eye Movement)잠이다. 깊은 잠은 말 그대로 푹 자는 것을 말한다. 몸의 피로를 푸는 게 깊은 잠의 주 기능이다. 잠들고 첫 4시간 사이에 두 번 정도 깊은 잠에 든다. 보통 네 시간만 자도 피로를 해소할 수 있다고 하는 것은 깊은 잠을 두 번 취하는 데 4시간정도 걸리기 때문이다. 개인 차이는 있지만, 하루 네 시간만 자도 생활이 유지된다는 게 근거 없는 말이 아닌 셈이다.
그렇다면, 수험생도 하루 4시간만 자도 되지 않냐고 반문할 수 있다. 매일 3-4시간 덜 잘 수 있다면, 그만큼 더 많은 시간을  공부에 할애할 수 있으니 솔깃할만도 하다. 그런데, 공부하는 학생에게는 나머지 3-4시간 잠이 매우 중요하다. REM수면 때문이다. 재빠른 눈의 움직임 (Rapid Eye Movement)이란 표현에서 보이듯 REM수면 중에는 눈을 빠르게 좌우로 움직이다. 뇌가 낮에 배운 것을 통합하고 있다는 신호다 (Stickgold, 2005). 그런데, 7-8시간정도 자면 REM 수면을 4-5회 경험한다. 즉, 4시간만 자면 REM수면은 2번 밖에 취하지 못한다. 그만큼 두뇌가 낮에 배운 것을 통합하는 기회가 줄어든다. 두뇌를 도서관에 비유한다면, REM수면은 구입한 도서를 찾아보기 쉽게 정리하는 과정이라고 보면 된다. 아무리 소장 서적의 수가 많아도, 체계적으로 정리해 놓지 않으면 책을 찾을 수 없다. 책의 수가 많아질수록 문제가 더 심각해 진다. 두뇌도 마찬가지다. 낮에 활동하는 시간에 공부한 내용이 많으면 많을수록 두뇌에 축적된 정보가 체계적으로 통합돼야 비로소 지식으로 써먹을 수 있게 된다. 실제로, 수면시간을 줄이면 기억력도 떨어지고, 이해력도 떨어진다. 

## 두뇌를 살리는 교육
한국 사회의 과도한 교육경쟁은 경쟁 그 자체가 아니라, 경쟁의 내용에 있다. 무작정 공부시간만 늘린다고 시험 성적 오르는게 아니란 것은 공부 잘하는 사람이면 누구나 안다. 공부에도 기술이 있다. 그러나, 기술보다 더 중요한게 있다. 바로 두뇌 자체가 좋아야 한다. 두뇌는 훈련을 통해 좋아진다. 우선 필요한 게 마음가짐이다. 성장형 마음가짐이 필요하다. 이를 위해서는 부모와 교사가 학생을 지도하는 마음가짐도 성장형이 돼야 한다. 모든 아이들은 적절하게 지도받으면 올바르게 클 수 있다는 자세를 갖고, 지능이 아닌, 노력을 칭찬해 주어야 한다. 노력에 대한 칭찬뿐 아니라, 두뇌는 노력을 통해 향상될 수 있다는 과학적 근거를 제공해 주는 것도 필요하다. 성장형 마음가짐의 중요성을 입증한 드웩은 브레이놀로지(www.brainology.us)라는 프로그램을 통해 학생들이 성장형 마음가짐을 갖도록 도와준다. 학생들은 새로운 것을 배울 때 두뇌의 신경세포들 사이에 새로운 연결구조가 형성되고, 이것이 뇌의 향상으로 이어진다는 사실을 알게 됨으로써, 성장형 마음가짐을 갖게 된다.
사람의 뇌는 사회뇌라고 한다. 3장에서 소개했듯, 사람의 지적 능력은 복잡한 사회를 이루는 과정에서 형성됐다. 사회뇌의 핵심이 되는 부분이 전전두엽이다. 다른 사람의 의도를 파악하고, 본인의 감정을 조절하는 작용이 전전두엽을 통해 이뤄지기 때문이다. 그런데, 전전두엽이 청소년기에 집중적으로 형성된다. 뇌는 물리적으로 형성하는 시기에 집중적으로 사용해야 잘 발달한다. 따라서, 전전두엽이 주로 발달하는 청소년기에 전전두엽을 집중적으로 사용할 수 있는 환경을 만들어 줘야 한다는 것이다. 그중 하나가 학생자치활동을 통해, 청소년들 스스로 사회관계를 만들고 이끌어 가도록 하는 것이다. 복잡한 사회관계를 통해 사람이 고도의 지능을 갖추게 됐듯, 청소년들도 복잡한 사회관계를 직접 경험할 때 두뇌 발달이 촉진될 수 있다. 사회뇌의 핵심 부위인 전전두엽을 집중적으로 사용해야 하는 활동이다. 전전두엽은 책상에 앉아 영어단어, 수학공식 하나 더 외운다고 발달되는 부위가 아니다. 한국의 교육 문화는 대학입시를 위해 중고등학생들의 자치활동을 희생시키는 경향이 있다. 공부시간을 늘릴 수는 있겠지만, 청소년들이 두뇌를 향상시킬 수 있는 황금 같은 기회를 저버리는 선택이다. 사람의 두뇌가 중요하다는 것은 너무나 당연한데도, 뜨거운 교육열이 청소년들의 두뇌 발달을 저해한다는 사실은 역설적이다.
명상을 정규교육 프로그램으로 도입하는 것도 적극 검토할 필요가 있다. 명상을 꾸준하게 할 경우, 주의 조절 능력이 향상된다. 주의 조절 능력 향상 효과는 앞서 소개한 지능 향상 효과에 국한되지 않는다. 감정조절능력, 사회기술, 및 자아 존중감 등은 향상되고, 시험불안감, 충동적 행동, 부정적 감정 등이 감소한다 (주: 명상을 교육에 활용한 사례는 미국 명상교육 협회 (Association for Mindfulness in Education: www.mindfuleducation.org)에서 찾을 수 있다. 실제로 미국 서남부 지역의 초등학교 두곳을 대상으로 24주간 마음챙김 명상 프로그램을 실시한 결과, 초등학교 학생들의 집중력 향상과 사회기술 증가 및 시험 불안감 등의 감소로 이어졌다 (Napoli, Krech, & Holley 2005).

