# 행복

## 욕망과 성취의 방정식

우리는 항상 무엇인가를 한다. 먹고 자고 쉬고 일하고 사고 쓰고... 그런데, 이 모든 것들을 왜 할까? 많은 사람들이 스마트폰과 같은 기기 좋아한다. 왜 스마트폰을 좋아하냐는 질문에 "멋있으니까, 트렌드니까, 편리하니까" 등 다양한 응답이 있을 수 있다. 이 질문에서 한단계 더 나아가, "왜 멋있는 것을 찾나요? 왜 트렌드를 찾죠? 왜 편리한 것을 찾죠?"라고 물을 수 있다. 이런 식으로 계속 "왜"라는 질문을 해나가다 보면 최종 도착점은 "즐거움"이다. 결국에는 "좋으니까"로 연결된다. 이런 식으로 근본적인 동기를 따지는 질문은 아리스토텔레스까지 거슬러 올라간다. 아리스토텔레스는 <니코마코스 윤리학>에서 행복의 추구가 인간의 행동을 근원적으로 규정하는 첫번째 원칙이라고 했다. 행복을 추구하는 동기가 사람의 가장 근본적인 욕구이며, 다른 모든 욕구 혹은 욕망은 행복을 추구하는 동기에서 비롯된다는 것이다. 생존을 위한 기본적인 욕구부터, 안전에의 욕구, 관계의 욕구, 명예의 욕구 등 모든 욕구와 욕망은 행복의 추구로 귀결된다. 성취를 통해 욕구와 욕망을 채울 수 있기에, 행복은 욕망에 반비례하고, 성취에 비례한다는 ‘행복의 방정식 (행복 = 성취 / 욕망)’을 만들어 낼 수 있다. 
행복의 방정식에 따르면 행복하게 살 수 있는 방법은 욕망은 최소화하면서, 성취를 극대화하는데 있다. 단순해 보이지만, 이 방정식을 실제로 적용하기는 결코 쉽지 않다. 욕망과 성취의 관계 때문이다. 5장 욕망에서 논의했듯, 욕망은 삶을 가능하게하는 원동력이다. 욕망은 무엇인가를 성취해내는 것이 가능하도록 하는 힘이다. 욕망을 줄이면, 그만큼 성취도 함께 줄어든다. 라이트 형제에게 하늘을 날고자 하는 강렬한 욕망이 없었더라면, 혹은 에디슨에게 전기로 세상을 밝히겠다는 열정이 없었더라면, 이들에게 비행기와 전구의 발명이라는 성취는 돌아가지 않았다. 성취에는 늘 피와 땀이 젖어 있기 마련인데, 그 피와 땀을 감내하도록 하는게 욕망이다. 이 행복의 방정식이 더 복잡해지는 요인이 있다. 한편으로 욕망이 있어야 성취가 가능해지지만, 다른 한편으로는 성취가 역으로 더 큰 욕망을 불러일으킨다.  

## 성취 역설
성취가 행복의 주요한 요인임에도 불구하고, 성취 때문에 욕망이 더욱 커져, 행복하지 못하는 현상은 ‘성취 역설’이라고 할 수 있다.  부 혹은 재산은 성취를 나타내는 전형적인 지표다. 사람의 욕망은 대체로 비슷하다고 봤을 때, 행복의 방정식을 액면 그대로 적용하면, 재산이 많을 수록 행복할 확률이 높아져야 한다. 그런데,  현실적으로 소득수준이 높다고 해서 반드시 행복하게 살지는 않는다.  지난 수십년간 전 세계 사람들의 소득수준이 크게 증가했지만, 사람들의 행복감은 소득수준 향상에 비례하지 않는다 (Easterling 1995). 소득수준이 극적으로 증가한 일본이 전형적인 예다. 일본의 소득은 1958년에서 1987년 사이 소득수준이 5배나 향상됐다. 생활수준의 급격한 향상에도 불구하고, 일본인들의 삶의 만족도는 1958년 이후 30여년간 거의 변하지 않았다.  이런 패턴은 미국이나 유럽 국가에서도 공통적으로 발견되는 현상이다. 이런 소득역설이 발생하는 이유 중 하나로 꼽히는 게 사회비교다. 절대적 수준의 소득은 향상됐지만, 늘 접하는 사람들 사이의 상대적 수준은 그리 달라진 게 없다. 
성취역설은 성취의 대표적인 지표인 돈의 역할을 통해서도 설명할 수 있다. 돈은 성취에 대한 욕구를 더욱 더 강화하는 경향이 있다. 수입이 늘면, 많은 것을 소비할 수 있어 만족도가 높아지기 보다, 더 많은 것을 소비하고 싶은 욕구가 더 강해진다. 행복 방정식대로, 욕구가 증가한다는 그만큼 행복감은 줄게 된다. 실제로 돈을 보기만 해도 사람들은 삶을 즐기는 능력을 잃게 되는 경향이 있다 (Quoidbach et al..2010). 벨기에 영국 미국의 연구팀은 벨기에의 한 대학교의 직원 351명을 대상으로 행복과 재산에 대한 설문조사를 실시했다. 설문 참가자들의 절반은 설문조사를 하면서 배경화면으로 커다란 돈뭉치 사진을 보았고, 나머지 절반은 돈뭉치 여부를 식별하기 어려운 사진을 보았다. 설문내용은 현재를 즐길수 있는 능력, 행복감, 미래의 부에 대한 열망 및 재산규모였다. 연구결과는 돈의 성격을 그대로 반영했다. 재산이 많은 사람일수록 현재를 즐기지 못하는 것으로 나타났다. 이뿐 아니다. 돈뭉치 사진을 보기만 해도 사람들의 현재를 즐기는 능력이 떨어졌다. 연구팀은 설문조사를 실험실에서 재현했다. 우선, 캐나다의 대학생 40명을 실험실로 초대했다. 참가자들에는 초콜렛의 맛을 테스트하는 연구라고 소개했다. 실험 참가자들은 임의로 두 집단으로 나뉘었다. 초콜렛에 대한 선호도 등에 질문하면서, 한 집단에는 설문항목의 배경에 돈뭉치 사진을 보여주었고, 대조집단에는 돈뭉치를 보여주지 않았다. 참가자들이 초콜렛을 먹는 동안, 연구진은 비밀리에 참가자들의 얼굴표정과 초콜렛을 먹는데 들인 시간을 기록했다. 참가자들이 초콜렛을 어느 정도 즐기는지 측정한 것이다. 돈뭉치를 보지 않은 참가자들은 평균 45초동안 초콜렛 한조각을 먹었다. 반면, 돈뭉치를 본 사람들은 약 30초만에 먹어 치웠다. 얼굴 표정도 달랐다. 돈뭉치를 보지 않은 사람들은 초콜렛 먹는 순간을 즐기고 있다는 것이 얼굴 표정에 드러났지만, 돈뭉치를 본 사람들은 대체로 덤덤했다.
성취가 반드시 행복으로 이어지지 않는 이유는 5장 욕구에서 지적한 것처럼 인간의 두뇌는 항상 적응하기 때문이다. 이미 갖고 있는 것에 익숙해지면서, 더 크고, 더 좋고, 더 많은 것을 기대하게 된다. 새로운 것을 얻게 되면 그 순간은 즐겁지만, 시간이 흐르면 익숙해지고 새로움은 더 이상 즐거움을 주기 못하게 된다. 주어진 조건에 만족하지 않고 지속적으로 새로운 기회를 찾아 나선 사람들이 보다 많은 것을 성취할 수 있었고, 그런 사람들의 후예가 바로 오늘날의 우리들이다. 앞으로 나가고 또 나가도, 계속 앞으로 나가도 만족하지 못하는 현상을 쾌락의 쳇바퀴(Hedonic Treadmill)라고 한다. 주어진 것에 안주하지 않는 성향이 생존과 번영을 가능하게 했지만, 현재의 순간 순간은 제대로 즐기지 못한다. 성취가 반드시 쾌락과 행복으로 연결되지 못하는 셈. 아무리 달려도 제자리에서 맴돌 뿐 저 앞에 잡힐 것 같은 행복은 손아귀에 들어오지 않는다. 그렇다고 쳇바퀴에서 나올 수도 없다. 달리기를 멈추면 그나마 현상유지도 안되기 때문이다. 
그렇다면 인간은 불행하게 살수 밖에 없는 운명일까? 불행하게도 그런 것 같기도 하다. 진화론을 정립한 다윈 역시 그렇게 진화한 인간 중의 하나였던 것 같다. 다윈 역시 여느 인간과 다름없이 쳇바퀴 안에서 열심히 달렸다. 다른 점이 있다면, 여느 인간보다 훨씬 더 열심히 달렸다는 것이다. ‘8장 교육’에서 소개했듯 다윈의 천재성은 지식에 대한 열정과 지독한 노력의 결과였다. 덕분에 인류의 역사에 중요한 업적을 남겼지만, 정작 다윈은 자신의 삶에 그리 만족하지 않았던 것 같다. 그의 자서전에서 다윈은 연구에 몰두하다, 시나 음악을 즐길 수 있는 마음의 여유자체를 잃어버린 그의 모습에 후회한다고 적고 있다. 

나의 마음은 지난 20,30년간 바뀌었다... 요 최근 몇년간 나는 시 한줄 읽는 것조차 감내하지 못하고 있다.... 나는 음악이나 그림에 대한 취향을 대부분 잃었다....  나의 마음은 일종의 기계가 된 것 같다. 거대한 자료의 더미에서 일반법칙을 추출해내는 기계말이다. … 
내가 만일 삶을 다시 한번 산다면, 삶의 규칙 하나를 마련하겠다. 최소한 일주일에 한번쯤은 시도 읽고 음악도 듣는 그런 삶 말이다… 시와 음악에 대한 취향을 잃어버리는 것은 행복의 상실과도 같다. 지적 능력에도 좋지 않은 것 같고, 심지어 도덕성에도 나쁜 영향을 미칠 듯 하다. 우리 인간 본성의 정서적 요인을 쇠약하게 하기 때문이다. 
-<찰스 다윈 자서전>에서 pp. 138-139

긍정심리학의 지평을 넓힌 바바라 프레드릭슨 역시 지난날을 돌아보며 다윈처럼 일벌레로 산 것을 후회하는 글을 남겼다. 바바라 프레드릭슨은 긍정 감정의 권위자인데, 지독한 일벌레였다고 한다. 프레드릭슨은 그의 저서 <긍정성>에서 "바바라, 넌 감정이 없으니까 감정연구하는 거지?"라는 말을 들을 정도로 연구에만 매달렸다고 회고했다. 그런데, 다윈이 연구에 미쳐 젊은 날을 일벌레로 지내지 않았더라면 진화론이 세상에 나오는데, 시간이 더 걸렸을 것이다. 프레드릭슨이 일벌레가 아니었더라면, 인류는 긍정성의 기능을 아직도 정확하게 파악하지 못하고 있을지도 모른다. 다윈과 프레드릭슨 말고도 진보를 이뤄낸 일벌레들의 예는 무수히 많다. 성공의 비결로 여겨지는 1만시간의 법칙은 일벌레들의 원칙이다. 매일 하루도 거르지 않고, 꼬박 8시간을 4년간 투자해야 이룰 수 있는게 1만시간이다. 이 8시간은 대충 채우는 시간이 아니다. 의도적으로 집중해야 하는 시간이다. 우리 인류는 그런 일벌레들이 이룩해 놓은 업적 덕에 풍요를 누리고 있다고 해도 과언이 아니다. 
역사적인 일벌레들은 왜 그들의 일에 열정을 쏟아 부었을까? 과연 그들은 그토록 일에 미쳐사는 것이 행복했을까?  ‘행복 = 성취 / 욕망’이라는 행복방정식만으로 그 답을 찾기 쉽지 않다. 성취와 욕망의 긴밀한 관계뿐 아니라, 행복이 무엇인지 확실하지 않기 때문이다. 행복은 주관적으로 삶의 만족을 의미하는 것일수도 있고, 객관적인 상태를 말하는 것일 수 있다. 이에 대해 학계에 일치된 의견이 없다. 행복의 주관적 요소를 강조하는 전통은 기원전 4세기까지 거슬러 올라갈 수 있다. 그리스 철학자 아리스티푸스는 행복은 즐거움을 최대화하는 것이 삶의 목적이며, 행복은 즐거운 순간의 총합이라고 했다. 기원전 3세기 에피쿠로스도 행복의 주관적 요소를 강조해, 삶의 경험이 즐거움으로 가득차는 것이 도덕적 의무라고 했다.  이 전통은 데이빗 흄과 제레미 벤담 등 영국 공리주의 철학의 기반이 됐다. 현대 심리학자들은 즐거움을 광범하게 정의한다. 행복은 감각적 쾌락 뿐 아니라, 삶의 전반적 만족감을 포괄하는 광범한 개념이다. 대표적인 예가, 에드 디너의 주관적 안녕감(Subjective Well-being)이다. 주관적 안녕감은 사람들의 삶에 대한 인지적, 감성적 평가를 말한다. 삶에 즐거움이 풍부하고, 흥미로운 일에 관여하고 있고, 부정적 정서가 적어, 삶의 만족도가 높다면 주관적 안녕감이 높다고 할 수 있다. 즉, 주관적 안녕감은 크게 세가지 요소가 있다. 삶의 만족감, 긍정적 감성의 존재, 부정적 감성의 부재다. 삶의 만족도는 전반적인 삶의 만족과 직업과 같은 각 영역별 만족도로 구분할 수 있다. 이 전통은 근대 행동경제학의 토대를 마련한 다니엘 카네만이 에드 디너 및 찰스 슈워츠와 공동으로 편집한 저서 <안녕감: 쾌락 심리학의 근본(Well-being: The foundations of Hedonic Psychology)> 에 집대성돼 있다. 
주관적 만족감과는 대조적으로, 행복의 객관적 상태를 강조하는 접근도 있다.  이 전통에서는 즐거움 자체를 행복과 동일시하는 경향을 속된 것으로 경시하며, 삶의 의미에 높은 가치를 부여한다. 대표적인 예가 아리스토텔레스가 <니코마키안 윤리학>에서 제시한 유대모니아(Eudaimonia: 자아(daimon)에 진실됨(eu-))다. 한 개인이 스스로의 잠재력을 실현하며 탁월함을 추구할 때 도달하는 상태다. 이 전통은 존 스튜어트 밀과 버트런트 러셀을 거쳐, 현대 심리학의 또 하나의 흐름을 이루고 있다. 아브람 마슬로의 자아실현이 대표적인 사례다. 이 전통에 따르면, 행복하기 위해 반드시 즐거운 상태가 유지돼야 하는 것은 아니다. 때론 주관적으로 힘들고 고통스러워도 객관적으로 개인의 잠재력을 충분히 실현한다면 행복한 것이라 할 수 있다. 주관적 쾌락보다는, 삶에 가치있는 것들을 추구하는 것이 행복을 추구하는 것이 된다. 객관적 상태를 강조하는 전통에서는 종종 ‘행복’이란 용어 앞에 ‘진정한’이란 수식어를 사용한다. 행복이란 주관적 행복감 이상의 것이라는 사고가 깔려있는 표현이다.
행복을 객관적 상태로 이해한다면, 다윈과 프레드릭슨 같은 ‘일벌레’들은 행복한 사람들이라고 할 수 있다. 그들의 잠재력을 충분히 발휘했다고 할 수 있기 때문이다. 비록 시와 음악을 즐기는 삶의 여유를 잃어, 삶의 순간 순간의 즐거움은 그리 많이 경험하지는 않더라도 말이다. ‘8장 교육’에서 성공의 비밀은 기개라고 논의한 것처럼, 일에 대한 열정이나 지독한 노력은 즐거움보다는 고통을 수반할 때가 많다. 행복을 주관적인 만족도나 즐거움으로 본다면, 성공을 위한 고통을 행복으로 설명하기 위해서는 몇가지 논리가 더 필요하다. 미래의 더 큰 행복을 위해 현재의 즐거움을 희생한다는 식으로 말이다. 반면, 객관적 상태로 본다면 성공을 위해 인내해 나가는 순간들을 그대로 행복으로 이해할 수 있다. 이런 점에서 행복을 객관적 상태로 파악하는 것이 주관적 만족감으로 이해하는 것보다 실용적인 측면이 있다.

## 행복역설
행복이란게 참 묘한 구석이 있어, "행복, 행복, 행복..." 하며 따라다니면, 항상 저 멀리 떨어져 있지, 내 손아귀에 들어오지 않는다. 오히려 행복에 큰 가치를 두는 사람들은 역설적으로 불행한 편이다. 행복에 가치를 부여하면 할 수록 삶에서 느끼는 행복함에 대한 실망감이 크기 때문이다. 행복에 가치를 두기 때문에 행복하게 살지 못한다고 해서 행복역설이라고 한다 (Mauss, Tamir, Anderson, Savino, in press). 행복역설과 성취역설은 비슷하지만 다른 점이 있다. 둘다 특정 목표를 설정해 놓고, 기대수준을 높여 놓았다는 점에서 비슷하다. 다른 점은 목표의 성격이다. 성취는 무엇인가 구체적으로 이뤄내는 것이 목표인 반면, 행복은 감정적 상태다. 구체적인 것에 대한 성취를 목표로 설정한 경우, 그 목표를 이룸으로써 무엇인가 구체적인 성과를 얻을 수 있다. 그런데, 행복처럼 감정적 상태를 목표로 하면, 무엇인가 구체적이로 이룰 수 있는 성과가 없다. 이런 점에서 행복역설에 빠지는 것이 성취역설보다 더 불행하게 된다. 
미국 덴버 대학의 아이리스 마우스와 보스턴대학의 마야 타밀 등의 연구진은 두차례의 연구를 통해 행복역설 현상을 보여주었다. 우선, 행복에 부여하는 가치와 실제 느끼는 행복감에 대해 설문조사를 실시했다. 설문내용은 (1) 행복에 얼마나 중요한 가치를 부여하는지, 행복하기 위해 얼마나 노력하는지 등의 행복가치, (2) 이혼, 가족과의 사별 등 삶에서 겪은 스트레스 정도, (3) 긍정 혹은 부정적인 느낌, (4) 삶에 대한 주관적 만족감, (5) 삶의 의미와 목표 등에 대한 심리적 안녕감, 그리고 (6) 우울증세 등이다. 결과는 행복에 가치를 부여하면 할 수록 부정적인 느낌이 컸고, 삶에 대한 주관적 만족감과 심리적 안녕감도 떨어졌다. 스트레스가 적은 사람들인 경우, 이런 경향이 더 강했다. 심지어 우울증세까지 보였다. 
연구진은 상관관계만을 나타내는 설문조사의 한계를 극복하기 위해 실험연구도 했다. 두 집단으로 나눠, 한쪽 집단은 행복의 과학에 대한 가짜 신문기사를 읽었다. 행복한 것이 사회관계를 좋게 하고, 사회적 성공으로 이어지며, 전반적으로 건강하게 산다는 내용이다. 다른 집단은 비슷한 내용의 가짜 신문기사를 읽었는데, ‘행복’이란 단어 대신 ‘정확한 판단’을 사용했다. 즉, 정확한 판단은 사회관계가 좋고, 사회적 성공으로 이어지며, 전반적으로 건강하게 산다는 내용이다. 신문기사를 읽은 다음 2분정도의 행복한 장면을 묘사한 영화장면을 보았다. 유명 피겨스케이트 선수가 금메달을 받고, 관중들의 환호속에 그녀의 코치와 승리를 축하하는 장면이었다. 영화를 본 다음, 행복함과 즐거움 및 슬픔 불안 긴장 등의 감정 상태에 대해 답했다. 결과는 설문조사와 일치했다. 행복에 가치를 두도록 한 집단은 행복한 영화를 보고도 그리 행복해 하지 않았다.
행복을 만족감이나 즐거움과 같은 주관적인 상태로 이해하고, 행복감을 추구하는 것이 역설적으로 사람들을 불행하게 만든다. 역으로 행복이란 것이 주관적으로 좋은 느낌보다는 어떤 객관적인 상태에 이르는 것이라고 여길 때 주관적으로 행복감을 느낄수 있다고도 할 수 있다. 개인의 잠재력을 충분히 발휘하는 자아실현이 객관적인 상태의 행복을 나타내는 좋은 예다. 나의 행복이 아닌, 다른 사람의 행복을 위해 돈과 시간을 쓸 줄 아는 사람이 되는 것도 객관적 상태의 행복을 나타내는 예다. 

## 고통의 역할
삶을 가능하게 하는 것은 즐거움만이 아니다. 고통 역시 생존과 종의 재생산에 중요한 역할을 한다. 슬픔, 분노, 공포 등은 모두 고통스런 경험이다. 이런 부정적인 정서를 경험할 수 없으면 살아남기 힘들다. 사자를 무서워하지 않는 개인은 일찌감치 사자의 밥이 됐을 것이다. 자신의 영역을 침해하는 외부인에 분노하지 않는 개인 역시 살아남기 어렵다. 가까운 사람 잃는 것을 슬퍼하지 않아도 마찬가지다. 9장 오락에서 논의했듯, 고통은 삶의 중요한 일부일 뿐 아니라, 성취하는데 반드시 수반되는 필수 조건이기도 하다. 올림픽 금메달을 목에 건 김연아 선수의 발은 상처투성이다. 한국 축구 대표선수인 박지성의 발 역시 수많은 상처와 굳은 살로 가득하다. 세계적인 발레리나 강수진의 발도 고된 연습의 흔적이 역력하게 남아았다. 이런 점에서 고통은 즐거움의 원천이 된다고도 할 수 있다. 실제로 사람이 보상을 통해 즐거움을 경험하도록 하는 두뇌의 작용을 보면 즐거움과 고통의 긴밀한 관계가 드러난다.
즐거움은 오피오이드가 뇌에서 분비될 때 경험하는데, 오피오이드는 사람의 몸안에서 합성되는 강력한 진통제다. 9장에서 소개했듯, 미국 미시건 대학의 켄트 베리지는 보상과 즐거움의 본질을 밝히면서 보상에 따른 즐거움을  ‘원함(wanting)’과 ‘좋아함(liking)’ 두가지 요소로 구분한다. ‘원함’은 욕망시스템이다. 도파민을 통해 작동한다. 보통 ‘원함’과 같은 욕망시스템은 즐거움과 긴밀하게 연결돼 있다. 이 ‘좋아함’시스템의 핵심 물질이 오피오이드다. 베리지의 가설은 코카인처럼 도파민 시스템에 작동하는 마약의 중독자를 통해서도 확인됐다. 코카인의 중독된 사람들은 ‘원함’시스템이 비정상적으로 과도하게 작동된 사람들이다. 이들의 뇌에서 코카인을 ‘미치도록’원하지만, ‘좋아함’ 반응은 미약하다. 베리지의 연구는 행복이 욕망의 크기와 반비례한다는 행복의 방정식과 일치한다. 욕망시스템인 도파민만으로는 즐거움을 경험할 수 없다는 근거를 제시하기 때문이다. 
욕망을 에너지삼아 성취를 이루는 과정에서 고통은 피할 수 없다. 이런 점에서 욕망은 고통의 원천이라고도 할 수 있다. 행복은 바로 그런 고통을 통해 이룩한 것에 대한 보상이라고 할 수 있다. 이런 점에서 고통없이 쾌락이나 행복을 구하려는 시도에는 부작용이 따르기 마련이다. 쾌락을 얻고자 마약을 투여하는 사례가 고통없는 행복의 부작용을 보여주는 좋은 사례다. 마약은 초기에는 좋을지 몰라도, 반복되면 즐거움은 사라진다. 헤로인이나 아편같은 진통제 계열의 마약에 중독된 다음, 약기운이 떨어지면, 통증에 상당히 민감해 진다. 진통효과에 몸이 적응하기 때문이다. 문에 살짝만 부딪혀도 극심한 통증을 느낀다고 생각해 보라. 그 다음에는 쾌락때문에 아편이나 헤로인을 찾는게 아니라, 고통을 피하기 위해 찾게 된다. 삶이 비참해지는 것이다. 이미 중독이 돼서 쾌락을 느끼는 역치는 올라갈 대로 올라가 어지간한 양의 약물로는 쾌락은 못느낀다. 오직 고통만 피할 수 있을 뿐. 약기운이 떨어지면 사소한 일 하나 하나가 고통의 연속이 된다. 각성제 계열의 코카인이나 필로폰 역시 중독에 대가는 가혹하다. 각성제는 쾌락 그 자체로 이어지는 역할을 하지 않는다. 무엇인가를 강력하게 원하도록 만드는 역할을 한다. 각성제는 ‘원함’에 관여하는 도파민 시스템만을 작동시키기 때문이다. 각성제 계열의 마약에 중독되면 무엇인가를 강하게 원하지만 만족감은 느낄 수 없는 상태가 되고 만다. 의식적으로는 분명히 그만 두고 싶고, 하기 싫어도, 하게 되는 상태가 된다. 좀비가 된다는 것이다.

## 행복하기
행복역설을 극복하는 방법은 두가지가 있다. 하나는 현재의 순간을 음미(savoring)하는 것이고, 다른 하나는 욕망을 조절하는 것이다. 욕망을 버리지는 못해도 욕망의 양을 줄이면 행복방정식의 행복감이 증가할 수 있다. 실제로 욕망의 양을 줄여 행복감을 경험하려는 사람들이 있다. 7월 13일자 보스턴 글로브에 따르면, 요즘 미국에서 세로퀴얼(Seroquel)로 알려진 쿼티아핀(Quetiapine)을 복용하는 사람들이 늘고 있다고 한다. 정신분열증 같은 환자들의 정서안정에 쓰이는 약인데, 건강한 사람들이 단지 안정을 취하기 위해 불법적으로 사용한다고 한다. 일반적으로 마약하면, 도파민을 분비시켜 성취지향의 쾌락을 경험하도록 하는 종류가 전형적이다. 도파민은 일종의 욕망의 물질이다. 기대와 욕망을 불러 일으켜, 그 욕망을 원동력 삼아 목표를 성취할 수 있는 원동력을 제공한다. 그런데, 그런 도파민의 분비를 차단하는 게 쿼티아핀의 기능이다. 욕망을 불러일으켜 성취를 극대화하는 것과 반대 방향이다. 나름대로 행복의 공식에 충실하다고 할 수 있다. 행복방정식대로 욕망의 양을 줄이는 것이 행복감의 크기를 키울 수 있기 때문이다. 그런데,  쿼티아핀에는 중독성이 있고, 약물에 중독되면, 장기적으로 행복하게 살기 어렵다. 게다가, 쿼티아핀에는 각종 부작용이 있다. 당뇨병이나 심혈관계통 질병에 노출되고, 급격하게 체중이 증가할 수도 있다고 한다.
마약과 같은 위험에 노출되지 않고 안전한 방법으로 욕망을 조절하는 방법은 없을까? 여러가지 방법이 있는데, 그중 하나가 욕망과 맞서 싸우는게 아니라, 욕망을 다스리는 방법이다. 즉, 양을 줄이지 말고, 욕망의 질을 바꾸는 전략이다. 유도가 좋은 비유다. 유도는 힘이 세다고 되는 운동이 아니다. 상대방의 힘을 역으로 이용할 수 있어야 한다. 특히, 나에게 가해지는 힘을 상대방에게 되돌리는 기술이 핵심이다. 욕망도 마찬가지다. 욕망이란 힘이 나에게 가해지면,  행복은 손아귀에 들어오지 않는다.  즉, "나, 나, 나"하며, "나"를 중심에 놓으면 욕망이 힘이 나에게 가해지게 된다. "나의 기분, 나의 행복, 나의 쾌감..." 이렇게 항상 나를 중심에 놓고 쾌락을 찾게 되면, 그 쾌락은 순간일 뿐이고, 지속되질 않는다. 행복역설에 빠지게 된다. 인간의 마음은 항상 쾌락에 적응하기 때문이다. 일단 익숙해 지면, 처음 경험했을 때의 즐거움은 사라진다. 그리고는 현실에 실망한다. 행복에 큰 가치를 두는 사람은 우울증세까지 보인다. 적응문제를 해결하는 방법 중 하나가 욕망의 힘을 다른 사람에게 가해지도록 하는 데 있다. 인터넷을 통해 널리 알려진 법륜스님의 주례사에 잘 나타나 있다 (법륜, 2002). "남의 덕 내가 보겠다"가 아니라, 내 덕을 다른 사람이 보게 하면 행복하게 살수 있다는 것이다. 다른 사람이 내 덕을 봐, 즐거울 때 느끼는 행복을 통해 성취역설을 극복할 수 있다는 것이다. 
과학자들은 남이 내 덕을 볼 때 정말로 인간이 쾌감을 느끼는지 다양한 방법으로 확인했다 (Dunn et al. 2008). 캐나다 브리티시 컬럼비아 대학 심리학과 엘리자베스 던의 연구팀은 미국인 632명을 대상으로 설문조사를 실시하면서, 전반적인 행복감과 함께, 연간소득 수준, 월별 소비 항목을 조사했다. 월별 소비항목은 두가지로 나눠, 본인은 위한 지출 (각종 비용, 본인을 위한 선물)과 타인을 위한 지출 (타인을 위한 선물,  자선을 위한 기부)로 구분했다. 조사 결과, 본인을 위한 지출은 행복감과 상관관계가 없었다. 반면, 타인을 위한 지출이 많을수록, 행복감이 높았다. 가외 소득이 생긴 사람들을 대상으로 한 조사에서도 비슷한 결과가 나왔다. 미국 보스턴의 한 기업이 직원들에게 상여금 5백만원 정도를 지급했다. 연구팀은 이 회사의 직원 16명의 행복감을 조사했다. 6주에서 8주 후에 행복감과 상여금 5백만원의 사용처를 조사했다. 앞선 설문조사와 마찬가지로 본인을 위해 지출한 비용은 행복감과 관계 없었지만, 타인을 위한 지출 규모가 클수록 행복감이 컸다. 연구팀은 인과관계를 입증하기 위해 실험도 했다. 실험 참가자들에게 5천원 혹은 2만원이 들어 있는 봉투를 오전에 나눠주며, 한 집단에는 본인을 위해 쓰라고 했고, 다른 집단에는 타인을 위해 쓰라고 했다. 그날 5시에 참가자들의 행복감을 조사했다. 타인을 위해 돈을 쓴 실험참가자들이 본인을 위해 돈을 쓴 사람들보다 더 행복감을 느꼈다. 받은 돈의 금액 (5천원 혹은 2만원) 사이의 차이는 없었다. 본인보다는 타인을 위해 돈을 쓰는 것이 더 행복감을 느끼게 하지만, 사람들은 반대로 여기는 경향이 있다. 던 연구팀의 조사에서도, 본인 혹은 타인을 위해 돈을 쓰는 것 중 어느 것이 더 행복할 것이냐는 설문 항목에서 상당수가 본인을 위해 돈을 쓰는 것이 더 행복할 것이라고 답했다. 
뇌 연구에서도 비슷한 결과가 나왔다. 미국 오리건 대학 경제학과 윌리엄 하보 연구팀은 실험 참가자들에게 10만원을 지급한 뒤, 지역 자선단체에 기부하도록 했다 (Harbaugh, Mayr, & Burghart, 2007). 참가자들은 두 집단으로 나뉘어, 한 집단은 기부 여부 및 금액은 참가자들이 자율적으로 선택했다. 다른 집단은 강제로 기부하도록 했다. 실험참가자들은 뇌영상장치 안에 누운 상태에서 컴퓨터 스크린을 통해 자신의 계정에서 돈이 빠져나가는 것을 보았다. 자율기부 조건의 참가자들은 기부여부에 대한 승인 혹은 거부버튼을 누를 수 있었다.  강제 기부 조건의 참가자들은 돈이 본인의 계정에서 빠져나간다는 사실을 인지한다는 버튼을 누를 수 있었다. 기부금은 5천원에서 4만 5천원까지 다양하게 설정됐다. 기부가 진행되는 동안 참가자들의 뇌 활동이 fMRI를 통해 기록됐다. 자율적으로 기부한 참가자와 강제로 기부한 참가자에게서 공통적으로 보상에 관여하는 두뇌 부위가 활성화했다. 즉, 남을 위해 돈을 쓰는 것이 직접적인 보상이 된다는 것이다. 위의 연구들은 돈으로 행복을 살수 있는 방법을 알려준 셈이다. 남을 위해 돈을 쓰면 되기 때문이다. 
3장에서 소개한 것처럼, 사람이 고도의 지능을 갖게 된 것은 복잡한 사회관계를 유지하기 위해서다. 인간의 지능이 복잡한 사회구조에서 비롯됐기에 ‘사회뇌 가설’이라고 한다. 이런 점에서 ‘인간은 사회적동물’이라는 것은 곧 ‘인간은 지적동물’이라고 하는 것과 본질적으로 같다고 할수 있다. 사회의 규모가 크다는 것은 단지 사람 수가 많다는 것만 의미하지 않다. 사회가 일정규모 이상을 유지하려면, "나"에 대한 범주를 확장시켜야 한다. 갑돌이가 "나"라고 할 때 "나"는 갑돌이 개체를 의미하지만, 갑돌이 "나"는 갑돌이의 가족이나 친척에까지 확장된다. 인간이 "나"의 범주를 갑돌이의 혈연수준까지만 확장할수 있는 수준일 때, 인간은 부족사회 정도의 문명을 이뤘다. "나"의 범주를 혈연에서, 민족으로 확장했을 때, 국가단위 정도의 문명을 이룩했다. 지구"촌"이란 개념이 나왔다는 것은 "나"의 범주를 모든 인류로 확장하려는 시도로 볼수 있다. 인간의 지적 능력이 복잡한 사회를 구성하는데서 왔듯, “나”의 범주를 확장한다는 것은 고도의 지적능력이 요구된다고 할 수 있다. 행복은 일종의 능력이라고도 할 수 있다. 자아의 범주를 확대하면서, 작은 자아의 이익을 유보하고, 커다란 자아의 이익을 도모할 수 있엉야 하기 때문이다.
