# References {.unnumbered}

::: {#refs}
:::

## 1장: 도덕

Watts, D. J. & Dodds, P. S. (2007). Influentials, networks, and public opinion formation. Journal of Consumer Research. 34, 441-458.

Slater, M. D. (2007). Reinforcing spirals: The mutual influence of media selectivity and media effects and their mutual impact on individual behavior and social identity. Communication Theory, 17, 281-303.

Pham, M. T. (2007). Emotion and rationality: A critical review and interpretation of empirical evidence. Review of General Psychology, 11. 155-178.

Sanfey, A. G., et al. (2003). The neural basis of economic decision-making in the ultimatum game. Science, 300. 1755-1758.
Greene J. D. et al. (2001). An fMRI investigation of emotional engagement in moral judgment. Science. 293, 2105-2108.

Haidt, J.  (2001). The emotional dog and its rational tail: Social intuitive approach to moral judgment. Psychological Review 108, 814-834.

Oaten, M, Stevenson, R. J., & Case, T. I, (2009). Disgust as a disease-avoidance mechanism. Psychological Bulletin, 135, 303-321.
Horberg, E. J., Oveis, C., Keltern, D., & Cohen, A. B. (2009).

Disgust and the moralization of purity. Journal of Personality and Social Psychology, 97, 963-976.

Schaller, M., & Duncan, L. A. (2007). The behavioral immune system: Its evolution and social psychological implications. In J. P. Forgas, M. G.Haselton, & W. von Hippel (Eds.), Evolution and the social mind: Evolutionary psychology and social cognition (pp. 293–307). New York: Psychology Press.

Inbar, Y., Pizarro, D. A., & Bloom, P. (2003. Conservatives are more easily disgusted than liberals. Cognition and Emotion, 23, 714-725.

Schaller, M. & Murray, D. R. (2008). Pathogens, personality, and culture: Disease prevalence predicts worldwide variability in sociosexuality, extraversion, and openness to experience. Journal of Personality and Social Psychology, 95, 212-221.

Thornhill, R. Fincher, C. L., & Aran, D. (2009). Parasites, democratization, and the liberalization of values across contemporary countries. Biological Review, 84, 113-131.

Faulkner, J., Schaller, M., Park, J. H., & Duncan, L. A. (2004). Evolved disease-avoidance mechanisms and contemporary xenophobic attitudes. Group Processes and Intergroup Behavior, 7, 333–53.

Haidt, J. (2007). The new synthesis in moral psychology. Science, 316, 998-1002.

## 2장: 권력

Carver, C. S., & White, T. L. (1994). Behaviral inhibition, behavioral activation and affective responses to impeding reward and punishment: The BIS/BAS scales. Journal of Personality and Social Psychology, 67, 319-333.

Carver, C. S., Harmon-Jones, E. (2009). Anger is an approach-related affect: Evidence and implication. Psychological Bulletin, 135, 183-204.

Keltner, D., Gruenfeld, D. H. & Anderson, C. (2003). Power, approach, and inhibition. Psychological Review. 110. 265-284.

Galinsky, A. D., Magee, J. C., Inesi, M. E., & Gruenfeld, D. H. (2007). Power and perspective not taken. Psychological Science. 17, 1068-1074.

Van Kleef, G. A., Oveis, C., van der Lowe, Ilmo, LuoKogan, A., Goetz, J., & Keltner, D. (2008). Power, distress, and compassion. Psychological Science, 19, 1315-1322.

Lammers, J., Stapel, D. A., Galinsky, A. D. (2010). Power increases hypocrisy, Psychological Science. 21, 737-744.

Lammers, J. Galinsly, A. D., Hordijn, E. H., & Otten, S. (2008). Illegitimacy moderates the effects of power on approach. Psychological Science. 19, 558-564.

## 3장: 매력

Tsukiura, T. & Cabeza, R. (2011). Shared brain activity for aesthetic and moral judgments: implications for the Beauty-is-Good stereotype. Social Cognitive and Affective Neuroscience, 6, 138-148.

Karremans, J. C., Frankenhuis, W. E., & Arons, S. (2010). Blind men prefer a low waist-to-hip ratio. Evolution and Human Behavior. 31, 182-186.

Lassek, W. D. & Gaulin, S. J. C. (2008). Waist-hip ratio and cognitive ability: is gluteofemoral fat a privileged store of neurodevelopmental resources? Evolution and Human Behavior. 29, 26-34.

Sugiyama, L. S. (2004). Is beauty in the context-sensitive adaptations of the beholder? Shiwiar use of waist-to-hip ratio in assessments of female mate value. Evolution and Human Behavior, 25, 51-62.

Miller, G. (2000). The mating mind: How sexual choice shaped the evolution of human nature. New York: Doubleday.

Stanik, C. E. & Ellsworth, P. C. (2010). Who cares about marrying a rich man? Intelligence and variation in women’s mate preferences. Human Nature, 2, 203-217.

Dunn, M., & Searle, R. (2010). Effect of manipulated prestige-car ownership on both sex attractiveness ratings. British Journal of Psychology, 101, 69-80.

Retrieved from http://www.businessweek.com/interactive_reports/philanthropy_individual.html

Dunbar, R. I. M. (1998). The social brain hypothesis. Evolutionary Anthropology, 6, 178-190.

Dunbar, R. I. M. & Shultz, S. (2007). Evolution in the social brain. Science. 317. 1344-1346.

Byrne, R. W., Whiten, A. (Eds.). (1988). Machiavellian Intelligence. Oxford: NY, Oxford University Press.

Porges, S. (2007). The polyvagal perspective. Biological Psychology, 74, 116-143.

Masi, C. M., Hawkley, L. C., Rickett, E. M., & Cacioppo, J. T. (2007). Respiratory sinus arrhythmia and disease of aging: Obesity, diabetes mellitus, and hypertension. Biological Psychology, 74, 212-223.

## 4장: 사랑

Peterson, C. (2006). A primer in positive psychology. New York: Oxford University Press.

Fisher, H. (1998). Lust, attraction, and attachment in mammalian reproduction. Human Nature. 9. 23-52.

Fisher, H., Aron, A., Machek, D., Li, H, & Brown, L. (2002). Defining the brain systems of lust, romantic attraction, and attachment. Archives of Sexual Behavior. 31, 413-419.

Fisher, H., Aron, A. Brown, L. (2006). Romantic love: A mammalian brain system for mate choice. Philosophical Transactions of the Royal Society B. 361, 2173-2186.

Fisher, H. (2006). Helen Fisher tells us why we  love + cheat. Retrieved from http://www.ted.com/talks/helen_fisher_tells_us_why_we_love_cheat.html.

Shostak, M. (1981) Nisa: the life and words of a !Kung woman. Cambridge, MA: Harvard University Press.

Kosfeld M, Heinrichs M, Zak PJ, Fischbacher U, Fehr E (2005): Oxytocin increases trust in humans. Nature, 435, 673-676.

Bartz, J. A., Zaki, J., Ochsner, K. N., Bolger, N., Kolevzon, A., Ludwig, N., et al. (2010). Effects of oxytocin on recollections of maternal care and closeness. Proceedings of the National Academy of Sciences, 107, 21371-21375.

Bartz, J. A., Zaki, J., Bolger, N., Hollander, E., Ludwig, N., Kolevzon, A. & Ochsner, K. N. (2010). Oxytocin selectively improves empathic accuracy in less socially proficient individuals. Psychological Science, 21, 1426-1428.

Campbell, A. (2007). Attachment, aggression and affiliation : the role of oxytocin in female social behavior. Biological psychology, 77, 1-10.

## 5장 욕망

김용규. ‘보바리 부인을 통해서 본 ‘욕망’의 의미. Retrieved from http://www.hani.co.kr/arti/culture/culture_general/277253.html
Small, D. M. et al. (2001).Changes in brain activity related to eating chocolate: From pleasure to aversion, Brain, 124, 1720-1733.

Kenrick, D. T., Griskevicius, V., Neuberg, S. L.& Schaller, M. (2010). Renovating the pyramid of needs: Contemporary extensions built upon ancient foundations. Perspectives on Psychological Science. 5. 292-314.

Maslow, A. H. (1943). A theory of human motivation. Psychological Review, 50, 370-396.

Griskevicius, V., Cialdini, R. B., & Kenrick, D. T. (2006). Peacocks, Picasso, and parental investment: The effects of romantic motive on creativity. Journal of Personality and Social Psychology, 91, 63-76.

Lyubomirsky, S. & Boehm, J. (2010). Human motives, happiness, and the puzzle of parenthood: Commentary on Kenrick et al. (2010). Perspectives on Psychological Science, 5, 327-334.

Kaplan, H.S., & Gangestad, S.W. (2005). Life history and evolutionary psychology. In D.M. Buss (Ed.), Handbook of evolutionary psychology (pp. 68–95). New York: Wiley.

Peterson, C., & Park, N. (2010). What happened to self-actualization? Commentary on Kenrick et al. (2010). Perspectives on Psychological Science, 5, 320–322.

Kesebir, S., Graham, J., & Oishi, S. (2010). A theory of human needs should be human-centered, not animal-centered: Commentary on Kenrick et al. (2010). Perspectives on Psychological Science, 5, 315–319.

Shaller, M., Neuberg, S. L., Griskevicius, V. & Kenrick, D. T. (2010). Pyramid power: A reply to commentaries. Perspectives on Psychological Science, 5, 335–337.

Henrich, J., Heine, S. J. & Norenzayan, A. (2010). The weirdest people in the world? Behavioral and Brain Sciences, 33, 61-135.

## 6장: 자살

WHO, Suicide prevention. Retrieved from http://www.who.int/mental_health/prevention/suicide/suicideprevent/en/

Hawton, K. & van Heerigen, K. (2009). Suicide, Lancet, 373, 1372-1381.

Voracek, M. (2004). National intelligence and suicide rate: An ecological study of 85 countries. Personality and Individual Differences, 37, 543-553.

De Catanzaro, D. (1995). Reproductive status, family interaction, and suicidal ideation: Surveys of the general public and high-risk groups. Ethology and Sociobiology, 16, 385-394.

Regnnante, R. A. et al. (2008). Clinical characteristics and four-year outcomes of patients in the Rhode Island Takotsubo cardiomyopathy registry. American Journal of Cardiology, 103, 1015-1019.

Williams, K. D. (2007). Osctracism: The kiss of social death. Social and Personality Psychology Compass, 1, 236-247.

Williams, K. D. (2007). Ostracism. Annual Review of Psychology, 58, 425-452.

Eisenberger, N. I., Lieberman, M. D., & Williams, K. D. (2003). Does rejection hurt? An fMRI study of social exclusion. Science,302, 290-292.

Stravynski, A. & Boyer, R. (2001). Loneliness in relation to suicide ideation and parasuicide: A population-wide study. Suicide and Life-Threatening Behavior, 31, 32-40.

Gilbert, D. T. & Wilson, T. D. (2007). Prospection : Experiencing the future. Science, 317, 1351-1354.

Morewedge, C. K., Gilbert, D. T. & Wilson, T. D. (2005). The least likely of times: How remembering the past biases forecasts of the future. Psychological Science, 16, 626-630.


## 7장: 선택

Bryant, J. & Zillmann, D. (1984). Using television to alleviate boredom and stress: Selective exposure as a function of induced excitational states. Journal of Broadcasting, 28, 1-20.

Strawson, G. (2010, July). Your move: The maze of free will, New York Times, Retrieved from http://opinionator.blogs.nytimes.com/2010/07/22/your-move-the-maze-of-free-will/

Sherif, M., Harvey, O. J., White, B. J., Hood, W. R., & Sherif, C. W. (1961). Intergroup cooperation and conflict: The robbers cave experiment. Norman, OK: University of Oklahoma Book Exchange.

Zimbardo, P. G. (2004). A situationist perspective on the psychology of evil: Understanding how good people are transform into perpetrators. In A. G. Miller (Ed.), The Social Psychology of Good and Evil (pp21-50). New York: Guildford Press.

Milgram, S. (1963). Behavioral study of obedience. Journal of Abnormal and Social Psychology, 67, 371-378.

Festinger, L., & Carlsmith, J. (1959). Cognitive consequences of forced compliance. Journal of Abnormal Psychology, 58, 203-210.

Harmon-Jones, E. & Harmon-Jones, C. (2008). Cognitive dissonance theory: An update with a focus on the action-based model. In J. Y. Shah & W. L. Gardner (Eds.), Handbook of motivation science, (pp. 71-83). New York: Guildford Press.

Libet, B., Gleason, C. A., Wright, E. W., & Pearl, D. K. (1983). Time of conscious intention to act in relation to onset of cerebral activity (readiness-potential): The unconscious initiation of a freely voluntary act. Brain, 106, 623-642.

Soon, C. S., Brass, M., Heinze, H-J. & Haynes, J-D. (2008). Unconscious determinants of free decisions in the human brain. Nature Neuroscience, 11, 543-545.

Wegner, D. M. & Wheatley, T. (1999). Apparent mental causation: Sources of the experience of will. American Psychologist, 54, 480-492.

Della Sala, S., Marchetti, C., & Spinnler, H. (1991). Right-sided anarchic (alien) hand: A longitudinal study. Neuropsychologia, 29, 1113–1127.

Bargh, J. A. (2005). Bypassing the will: Toward demystifying the nonconscious control of social behavior. The new unconscious. In R. R. Hassin, J. S. Uleman, J. A. Bargh (pp. 37-58). New York: Oxford University Press.

Baumeister, R. F., Vohs, K. D., & Tice, D. M. (2007). The strength model of self-control. Current Directions in Psychological Science, 16, 351-355.

Iyengar, S. (2010). The art of choosing. New York: Twelve.

Lutz, A. Slagter, H. A., Dunne, J. D,. & Davidson, R. J. (2007). Attention regulation and monitoring in meditation. Trends in Cognitive Science, 12, 163-169.

## 8장: 교육

Sackett, P. R., Borneman, M. J. & Connelly, B. S. (2008). High-stakes testing in higher education and employment: Appraising the evidence for validity and fairness. American Psychologist, 63, 215-227.

Darwin, C. (1853) Letter from Darwin to Galton, Retrieved from http://galton.org/letters/darwin/correspondence.htm.

Duckworth, A. L., Peterson, C., Matthews, M. D. & Kelly D. R. (2007). Grit: Perseverance and passion for long-term goals. Journal of Personality and Social Psychology, 92, 1087-1101.

Ericsson, K. A., Krampe, R., & Tesch-Romer, C. (1993). The role of deliberate practice in the acquisition of expert performance. Psychological Review, 100, 363-406.

Brooks, D. (2008, December). Lost in the crowd. New York Times, Retrieved from http://www.nytimes.com/2008/12/16/opinion/16brooks.html?_r=2&partner=permalink&exprod=permalink

Gladwell, M. (2008). Brooks on outliers. Gladwell.com, Retrieved from http://gladwell.typepad.com/gladwellcom/2008/12/brooks-on-outliers.html

Brooks, D. (2009). Genius: The modern view. New York Times, Retrieved from http://www.nytimes.com/2009/05/01/opinion/01brooks.html

Lenroot, R. K. & Giedd, J. N. (2006). Brain development in children and adolescents: Insights from anatomical magnetic resonance imaging. Neuroscience and Biobehavioral Review, 30, 718-729.

Jaeggi, S. M., Buschkuehl, M., Jonides, & Perrig, W. J. (2008). Improving fluid intelligence with training on working memory. PNAS, 105, 6829-6833.

Tang, Y-Y. et al. (2007). Short-term meditation training improves attention and self-regulation. PNAS, 104, 17152-17156.

Zeidan, F. et al. (2010). Mindfulness meditation improves cognition: Evidence of brief mental training. Consciousness and Cognition, 19, 597-605.

Short, B. E., Kose, S., Mu, Q., Borckardt, J., Newberg, A., George, M. S., et al (2007). Regional brain activation during meditation shows time and practice effects: An exploratory FMRI Study. Evidence Based Complementary and Alternative Medicine: eCAM. doi:10.1093/ecam/nem163.

Jaeggi et al. (2007). On how high performers keep cool brains in situations of cognitive overload. Cognitive, Affective, & Behavioral Neuroscience, 7, 75-89.

Magen, E. & Gross, J. (2007). Harnessing the need for immediate gratification: Cognitive reconstrual modulates the reward valued of temptations. Emotion, 7, 415-428.

Blackwell, L., Trzesniewski, K., & Dweck, C. S. (2007). Implicit theories of intelligence predict achievement across an adolescent transition: A longitudinal study and intervention. Child Development, 78, 246–263.

Dweck, C. S. (2007, December). The secret to raising smart kids. Scientific American Mind, Retrieved from http:// www.sciam.com/article.cfm?id=thesecrettoraisingsmartkids.

Mueller, C. M., & Dweck, C. S. (1998). Intelligence praise can undermine motivation and performance. Journal of Personality and Social Psychology, 75, 33–52.

동아일보 (2010, 7월) 중고교에 체육시간이 없다. Retrieved from http://localen.donga.com/F_Region/3/01/20100721/30026162/1

오마이뉴스 (2010, 4월) 놀 시간 없는 초등학생들, 체육시간도 빼앗겼다. Retrieved from http://www.ohmynews.com/NWS_Web/view/at_pg.aspx?CNTN_CD=A0001368094&PAGE_CD=.

Hillman, C. H., Erickson, K. I. & Kramer, A. F. (2008). Be smart, exercise your heart: Exercise effects on brain and cognition. Nature Reviews Neuroscience, 9, 58-65.

Stickgold, R. (2005). Sleep-dependent memory consolidation. Nature, 437, 1272-1278.

Napoli, M., Krech, P. R., & Holley, L. C. (2005). Mindfulness training for elementary school students: The attention academy. Journal of Applied School Psychology, 21, 99-125.

Bishop, S.R., Lau, M., Shapiro, S., Carlson, L.E., Anderson, N.D., Carmody, J., . . . Devins, G. (2004). Mindfulness: A proposed operational definition. Clinical Psychology: Science and Practice, 11, 230–241.

Kabat-Zinn, J. (1990). Full catastrophe living. New York, NY: Delta.

Hölzel, B.K., Ott, U., Hempel, H., Hackl, A., Wolf, K., Stark, R., & Vaitl, D. (2007). Differential engagement of anterior cingulate and adjacent medial frontal cortex in adept meditators and nonmeditators. Neuroscience Letters, 421, 16–21.

Farb, N.A.S., Segal, Z.V., Mayberg, H., Bean, J., McKeon, D., Fatima, Z., & Anderson, A.K. (2007). Attending to the present: Mindfulness meditation reveals distinct neural modes of selfreference. Social Cognitive and Affective Neuroscience, 2, 313-322.

## 9장: 쾌락 

Tamborini, R. (2003). Enjoyment and social functions of horror. In J. Bryant, D. Roskos-Ewoldsen & J. Cantor (Eds.), Communication and emotion: Essays in honor of Dolf Zillmann (pp. 417-443). Mahwah, NJ: Erlbaum.

Bushman, B. J. (2002). Does venting anger feed or extinguish the flame? Catharsis, rumination, -distraction, anger, and aggressive responding. Personality and Social Psychology Bulletin,28, 724-731.

Zillmann, D., Katcher, A. H., & Milavsky, B. (1972). Excitation transfer from physical exercise to subsequent aggressive behavior. Journal of Experimental Social Psychology, 8, 247-259.

Gross, J. J., Fredrickson, B. L., & Levenson, R. W. (1994). The psychophysiology of crying. Psychophysiology, 31, 460-468.

Rottenberg, J., Bylsma, L. M., & Vingerhoets, A. (2008). Is crying beneficial? Current Directions in Psychological Science, 17, 400-404.

Knutson, B. (2004). Sweet revenge. Science, 305, 1246-1247.

Zillmann, D. (2006). Empathy: Affective reactivity to others' emotional experiences. In J. Bryant & P. Vorderer (Eds.), Psychology of entertainment (pp. 151-181). Mahwah, NJ: Erlbaum.

Zillmann, D. & Bryant, J. (1975). Viewer’s moral sanction of retribution in the appreciation of dramatic presentations. Journal of Experimental Social Psychology, 11, 572-582.

Berridge, K. C. & Kringelbach, M. L. (2008). Affective neuroscience of pleasure: Reward in humans and animals. Psychopharmcology, 199, 457-480.

Fields, H. L. (2007). Understanding how opioids contribute to reward and analgesia. Regional Anesthesia and Pain Medicine. 32, 242–246.

Peterson, C. (2006). A primer in positive psychology. New York: Oxford University.

Oliver, M. B. (1993). Exploring the paradox of the enjoyment of sad films. Human Communication Research, 19, 315-342.

Mares, M. L., & Cantor, J. (1992). Elderly viewers' responses to televised portrayals of old age: Empathy and mood management versus social comparison. Communication Research, 19, 459-478.

Oliver, M. B. (2008). Tender affective states as predictors of entertainment preference. Journal of Communication, 58, 40-61. 

Pyszczynski, T., Greenberg, J., & Solomon, S. (1997). Why do we need what we need? A terror management perspective on the roots of human social motivation. Psychological Inquiry, 8, 1-20.

Zillmann, D., Weaver, J. B., Mundorf, N., & Aust, C. F. (1986). Effects of an opposite-gender companion's affect to horror on distress, delight, and attraction. Joumal of Personality and Social Psychology, 51, 586-594.

## 10장: 행복
Easterling, R. A. (1995). Will raising the income of all increase the happiness of all? Journal of Economic Behavior & Organization, 27, 35-47.

Quoidbach, J.,  Dunn, E. W., Petrides, K. V., & Mikolajczak, M. (2010) Money giveth, money taketh away: The dual effect of wealth on happiness. Psychological Science, 21, 759-763.

Mauss, I. B., Tamir, M., Anderson, C. L., & Savino, N. S. (2011). Can seeking happiness make people unhappy? Paradoxical effects of valuing happiness. Emotion, 11(4), 807–815. https://doi.org/10.1037/a0022010

Barlow, N. ed. (1958) The autobiography of Charlese Darwin 1809-1882: With the original omissions restored. Edited and appendix and notes by his grand-daughter Nora Barlow.. London: Collins, Retrieved from http://darwin-online.org.uk/content/frameset?itemID=F1497&viewtype=text&pageseq=1

Boston Globe (2009.7). Psychiatric drug sought on streets, Retrieved from  http://www.boston.com/news/education/higher/articles/2009/07/13/psychiatric_pill_thriving_on_streets_as_sedative/)

법륜 (2002). 법륜스님 주례사. Retrieved from http://www.jikji.org/%EB%B2%95%EB%A5%9C%EC%8A%A4%EB%8B%98%20%EC%A3%BC%EB%A1%80%EC%82%AC

Dunn, E. W., Aknin, L. B. Norton, M. I. (2008). Spending money on others promotes happiness. Science, 319, 1687-1688.
Harbaugh, W. T., Mayr, U., Burghart, D. R. (2007). Neural responses to taxation and volutary givign reveal motives for charitable donations. Science, 316, 1622-1625.
